class Microwave
{
	static String brand="Panasonic";
	static long price=6440L;
	static String model="NN-ST26JMFDG";
	static String energyConsumption="800 Watts";
	static String capacity="20 litres";
	static String annualEnergyConsumption="800 Watts";
	static String installationType="Countertop";
	static String partNumber="NN-ST26JMFDG";
	static String specialFeatures="Defrost,Turntable,Auto Heat,Timer,Compact,Vapor Clean,Auto Cook";
	static String ovenCookingMode="Solo";
	static String burnerType="Cast Iron";
	static String colour="Silver";
	static String voltage="230 Volts";
	static String wattage="800 Watts";
	static String fuelType="Electric";
	static String defrostSystem="Defrost";
	static String doorOrientation="Left";
	static String material="Iron";
	static String includedComponents="MWO Unit, Turntable, Rotating Ring, User Manual";
	static String batteriesIncluded="No";
	static String batteriesRequired="No";
	static String manufacturer="Panasonic";
	static String counteryOfOrigin="Thiland";
	public static void main(String [] args)
	{
		System.out.println("Microwave Brade is: "+brand);
		System.out.println("Microwave Price is: "+price);
		System.out.println("Microwave Model is: "+model);
		System.out.println("Microwave Energy Consumption is: "+energyConsumption);
		System.out.println("Microwave Capacity is: "+capacity);
		System.out.println("Microwave Annual Energy Consumption is: "+annualEnergyConsumption);
		System.out.println("Microwave Installation Type is: "+installationType);
		System.out.println("Microwave Part Number is: "+partNumber);
		System.out.println("Microwave special Features is: "+specialFeatures);
		System.out.println("Microwave Oven Cooking Mode is: "+ovenCookingMode);
		System.out.println("Microwave Burner Type is: "+burnerType);
		System.out.println("Microwave Colour is: "+colour);
		System.out.println("Microwave Voltage is: "+voltage);
		System.out.println("Microwave Wattage is: "+wattage);
		System.out.println("Microwave FuelType is: "+fuelType);
		System.out.println("Microwave Defrost System is: "+defrostSystem);
		System.out.println("Microwave DoorOrientation is: "+doorOrientation);
		System.out.println("Microwave Material is: "+material);
		System.out.println("Microwave Included Components is: "+includedComponents);
		System.out.println("Microwave Batteries Included is: "+batteriesIncluded);
		System.out.println("Microwave Batteries Required is: "+batteriesRequired);
		System.out.println("Microwave Manufacturer is: "+manufacturer);
	}
}