class Briefcase
{
	static long prize=15999;
	static	boolean isDiscontinuedByManufacturer=false;
	static	String productDimensions="43 x 10.5 x 32 cm; 1 kg";
	static	String dateFirstAvailable="3 June 2020";
	static	String asin="B089MCCTZH";
	static	String itemModelNumber="BRF706BR";
	static	String countryOfOrigin="India";
	static	String department="Unisex";
	static	String manufacturer="HINDUSTAN FOAM 9831172714, Hindustan Foam";
	static	String packer="HINDUSTAN FOAM, 16M GOLAM JILANI KHAN ROAD, KOLKATA 700039,9831172714";
	static	String importer="HINDUSTAN FOAM, 16M GOLAM JILANI KHAN ROAD, KOLKATA 700039,9831172714";
	static	String itemWeight="1 kg";
	static	String itemDimensionsLxWxH="43 x 10.5 x 32 Centimeters";
	static	String netQuantity="1.00 Count";
	static String includedComponents="Handbag";
	static String genericName="Briefcase Bag";
	public static void main(String args[])
	{
		long prize=14880L;
		boolean isDiscontinuedByManufacturer=false;
		productDimensions="43 x 10.5 x 32 cm; 1 kg";
		dateFirstAvailable="3 June 2020";
		asin="B089MCCTZH";
		itemModelNumber="BRF706BR";
		countryOfOrigin="India";
		department="Unisex";
		manufacturer="HINDUSTAN FOAM 9831172714, Hindustan Foam";
		packer="HINDUSTAN FOAM, 16M GOLAM JILANI KHAN ROAD, KOLKATA 700039,9831172714";
		importer="HINDUSTAN FOAM, 16M GOLAM JILANI KHAN ROAD, KOLKATA 700039,9831172714";
		itemWeight="1 kg";
		itemDimensionsLxWxH="43 x 10.5 x 32 Centimeters";
		netQuantity="1.00 Count";
		includedComponents="Handbag";
		genericName="Briefcase Bag";
		System.out.println("Briefcase Prize is: "+prize);
		System.out.println("Is Discontinued By Manufacturer is: "+isDiscontinuedByManufacturer);
		System.out.println("Product Dimensions is: "+productDimensions);
		System.out.println("Date First Available is: "+dateFirstAvailable);
		System.out.println("Manufacturer is: "+manufacturer);
		System.out.println("ASIN is: "+asin);
		System.out.println("Item model number is: "+itemModelNumber);
		System.out.println("Country of Origin is: "+countryOfOrigin);
		System.out.println("Department is: "+department);
		System.out.println("Manufacturer is: "+manufacturer);
		System.out.println("Packer is: "+packer);
		System.out.println("Importer is: "+importer);
		System.out.println("Item Weight is: "+itemWeight);
		System.out.println("Item Dimensions LxWxH is: "+itemDimensionsLxWxH);
		System.out.println("Net Quantity is: "+netQuantity);
		System.out.println("Included Components is: "+includedComponents);
		System.out.println("Generic Name is: "+genericName);
		System.out.println("-------------------------------------");
		System.out.println("Briefcase Prize is: "+Briefcase.prize);
		System.out.println("Is Discontinued By Manufacturer is: "+Briefcase.isDiscontinuedByManufacturer);
		System.out.println("Product Dimensions is: "+Briefcase.productDimensions);
		System.out.println("Date First Available is: "+Briefcase.dateFirstAvailable);
		System.out.println("Manufacturer is: "+Briefcase.manufacturer);
		System.out.println("ASIN is: "+Briefcase.asin);
		System.out.println("Item model number is: "+Briefcase.itemModelNumber);
		System.out.println("Country of Origin is: "+Briefcase.countryOfOrigin);
		System.out.println("Department is: "+Briefcase.department);
		System.out.println("Manufacturer is: "+Briefcase.manufacturer);
		System.out.println("Packer is: "+Briefcase.packer);
		System.out.println("Importer is: "+Briefcase.importer);
		System.out.println("Item Weight is: "+Briefcase.itemWeight);
		System.out.println("Item Dimensions LxWxH is: "+Briefcase.itemDimensionsLxWxH);
		System.out.println("Net Quantity is: "+Briefcase.netQuantity);
		System.out.println("Included Components is: "+Briefcase.includedComponents);
		System.out.println("Generic Name is: "+Briefcase.genericName);
	}
}