class HomeDecorativeItems
{
	static long prize=56L;
	static	String countryOfOrigin="IndiCountry of Origina";
	static	String productDimensions="IndiCountry of Origina";
	static	String shape="round";
	static	String itemWeight="5 gram";
	static	String style="desk";
	static	String prePrinted="yes";
	static	String manufacturer="IndiCountry of Origina";
	static	String itemPartNumber="K5Dyhu5";
	static	String asin="TUTH9654CGT";
	public static void main(String args[])
	{
		long prize=238L;
		String countryOfOrigin="IndiCountry of Origina";
		String productDimensions="IndiCountry of Origina";
		String shape="round";
		String itemWeight="5 gram";
		String style="desk";
		String prePrinted="yes";
		String manufacturer="IndiCountry of Origina";
		String itemPartNumber="K5Dyhu5";
		String asin="TUTH9654CGT";
		System.out.println("Brand Prize is: "+prize);
		System.out.println("Country of Origin is: "+countryOfOrigin);
		System.out.println("productDimensions is: "+productDimensions);
		System.out.println("Shape is: "+shape);
		System.out.println("itemWeight is: "+itemWeight);
		System.out.println("style is: "+style);
		System.out.println("prePrinted is: "+prePrinted);
		System.out.println("manufacturer is: "+manufacturer);
		System.out.println("itemPartNumber is: "+itemPartNumber);
		System.out.println("ASIN is: "+asin);
		System.out.println("-------------------------------------");
		System.out.println("Brand Prize is: "+HomeDecorativeItems.prize);
		System.out.println("Country of Origin is: "+HomeDecorativeItems.countryOfOrigin);
		System.out.println("productDimensions is: "+HomeDecorativeItems.productDimensions);
		System.out.println("Shape is: "+HomeDecorativeItems.shape);
		System.out.println("itemWeight is: "+HomeDecorativeItems.itemWeight);
		System.out.println("style is: "+HomeDecorativeItems.style);
		System.out.println("prePrinted is: "+HomeDecorativeItems.prePrinted);
		System.out.println("manufacturer is: "+HomeDecorativeItems.manufacturer);
		System.out.println("itemPartNumber is: "+HomeDecorativeItems.itemPartNumber);
		System.out.println("ASIN is: "+HomeDecorativeItems.asin);
	}
}
		