class JarCandles
{
	static long prize=3000L;
	static	String brand="India";
	static	String productDimensions="28 x 13 x 9 cm; 600 g";
	static	String itemWeight="300 gram";
	static	String numberOfItems="4";
	static	String scent="India";
	static	String material="India";
	static	String netQuantity="3";
	static	String manufacturer="Jar Candles";
	static	String partNumber="257TYGJ";
	static	String batteries="3";
	static	String countryOfOrigin="India";
	public static void main(String args[])
	{
		long prize=1000L;
		String brand="India";
		String productDimensions="28 x 13 x 9 cm; 600 g";
		String itemWeight="200 gram";
		String numberOfItems="2";
		String scent="India";
		String material="India";
		String netQuantity="5";
		String manufacturer="Jar Candles";
		String partNumber="6886BHHI";
		String batteries="6";
		String countryOfOrigin="India";
		System.out.println("JarCandles Prize are: "+prize);
		System.out.println("Brand is: "+brand);
		System.out.println("Product Dimensions is: "+productDimensions);
		System.out.println("Item Weight is: "+itemWeight);
		System.out.println("Number of Items is: "+numberOfItems);
		System.out.println("scent is: "+scent);
		System.out.println("Material is: "+material);
		System.out.println("Net Quantity is: "+netQuantity);
		System.out.println("Manufacturer is: "+manufacturer);
		System.out.println("Part Number is: "+partNumber);
		System.out.println("Batteries Required is: "+batteries);
		System.out.println("Country of Origin is: "+countryOfOrigin);
		System.out.println("-------------------------------------");
		System.out.println("JarCandles Prize are: "+JarCandles.prize);
		System.out.println("Brand is: "+JarCandles.brand);
		System.out.println("Product Dimensions is: "+JarCandles.productDimensions);
		System.out.println("Item Weight is: "+JarCandles.itemWeight);
		System.out.println("Number of Items is: "+JarCandles.numberOfItems);
		System.out.println("scent is: "+JarCandles.scent);
		System.out.println("Material is: "+JarCandles.material);
		System.out.println("Net Quantity is: "+JarCandles.netQuantity);
		System.out.println("Manufacturer is: "+JarCandles.manufacturer);
		System.out.println("Part Number is: "+JarCandles.partNumber);
		System.out.println("Batteries Required is: "+JarCandles.batteries);
		System.out.println("Country of Origin is: "+JarCandles.countryOfOrigin);
	}
}
		