class Microwave
{
	static String brand="Panasonic";
	static long price=7699L;
	static String model="NN-ST26JMFDG";
	static String energyConsumption="800 Watts";
	static String capacity="20 litres";
	static String annualEnergyConsumption="800 Watts";
	static String installationType="Countertop";
	static String partNumber="NN-ST26JMFDG";
	static String specialFeatures="Defrost,Turntable,Auto Heat,Timer,Compact,Vapor Clean,Auto Cook";
	static String ovenCookingMode="Solo";
	static String burnerType="Cast Iron";
	static String colour="Silver";
	static String voltage="230 Volts";
	static String wattage="800 Watts";
	static String fuelType="Electric";
	static String defrostSystem="Defrost";
	static String doorOrientation="Left";
	static String material="Iron";
	static String includedComponents="MWO Unit, Turntable, Rotating Ring, User Manual";
	static String batteriesIncluded="No";
	static String batteriesRequired="No";
	static String manufacturer="Panasonic";
	static String counteryOfOrigin="Thiland";
	public static void main(String [] args)
	{
		String brand="Panasonic";
		long price=6440L;
		String model="NN-ST26JMFDG";
		String energyConsumption="800 Watts";
		String capacity="20 litres";
		String annualEnergyConsumption="800 Watts";
		String installationType="Countertop";
		String partNumber="NN-ST26JMFDG";
		String specialFeatures="Defrost,Turntable,Auto Heat,Timer,Compact,Vapor Clean,Auto Cook";
		String ovenCookingMode="Solo";
		String burnerType="Cast Iron";
		String colour="Silver";
		String voltage="230 Volts";
		String wattage="800 Watts";
		String fuelType="Electric";
		String defrostSystem="Defrost";
		String doorOrientation="Left";
		String material="Iron";
		String includedComponents="MWO Unit, Turntable, Rotating Ring, User Manual";
		String batteriesIncluded="No";
		String batteriesRequired="No";
		String manufacturer="Panasonic";
		String counteryOfOrigin="Thiland";
		System.out.println("Microwave Brade is: "+brand);
		System.out.println("Microwave Price is: "+price);
		System.out.println("Microwave Model is: "+model);
		System.out.println("Microwave Energy Consumption is: "+energyConsumption);
		System.out.println("Microwave Capacity is: "+capacity);
		System.out.println("Microwave Annual Energy Consumption is: "+annualEnergyConsumption);
		System.out.println("Microwave Installation Type is: "+installationType);
		System.out.println("Microwave Part Number is: "+partNumber);
		System.out.println("Microwave special Features is: "+specialFeatures);
		System.out.println("Microwave Oven Cooking Mode is: "+ovenCookingMode);
		System.out.println("Microwave Burner Type is: "+burnerType);
		System.out.println("Microwave Colour is: "+colour);
		System.out.println("Microwave Voltage is: "+voltage);
		System.out.println("Microwave Wattage is: "+wattage);
		System.out.println("Microwave FuelType is: "+fuelType);
		System.out.println("Microwave Defrost System is: "+defrostSystem);
		System.out.println("Microwave DoorOrientation is: "+doorOrientation);
		System.out.println("Microwave Material is: "+material);
		System.out.println("Microwave Included Components is: "+includedComponents);
		System.out.println("Microwave Batteries Included is: "+batteriesIncluded);
		System.out.println("Microwave Batteries Required is: "+batteriesRequired);
		System.out.println("Microwave Manufacturer is: "+manufacturer);
		System.out.println("Microwave Countery Of Origin is: "+counteryOfOrigin);
		System.out.println("-------------------------------------");
		System.out.println("Microwave Brade is: "+Microwave.brand);
		System.out.println("Microwave Price is: "+Microwave.price);
		System.out.println("Microwave Model is: "+Microwave.model);
		System.out.println("Microwave Energy Consumption is: "+Microwave.energyConsumption);
		System.out.println("Microwave Capacity is: "+Microwave.capacity);
		System.out.println("Microwave Annual Energy Consumption is: "+Microwave.annualEnergyConsumption);
		System.out.println("Microwave Installation Type is: "+Microwave.installationType);
		System.out.println("Microwave Part Number is: "+Microwave.partNumber);
		System.out.println("Microwave special Features is: "+Microwave.specialFeatures);
		System.out.println("Microwave Oven Cooking Mode is: "+Microwave.ovenCookingMode);
		System.out.println("Microwave Burner Type is: "+Microwave.burnerType);
		System.out.println("Microwave Colour is: "+Microwave.colour);
		System.out.println("Microwave Voltage is: "+Microwave.voltage);
		System.out.println("Microwave Wattage is: "+Microwave.wattage);
		System.out.println("Microwave FuelType is: "+Microwave.fuelType);
		System.out.println("Microwave Defrost System is: "+Microwave.defrostSystem);
		System.out.println("Microwave DoorOrientation is: "+Microwave.doorOrientation);
		System.out.println("Microwave Material is: "+Microwave.material);
		System.out.println("Microwave Included Components is: "+Microwave.includedComponents);
		System.out.println("Microwave Batteries Included is: "+Microwave.batteriesIncluded);
		System.out.println("Microwave Batteries Required is: "+Microwave.batteriesRequired);
		System.out.println("Microwave Manufacturer is: "+Microwave.manufacturer);
		System.out.println("Microwave Countery Of Origin is: "+Microwave. counteryOfOrigin);

	}
}