class Necklace
{
	static long prize=900L;
	static String productDimensions="50.8 x 3 x 3 cm; 50 g";
	static	String dateFirstAvailable="3 October 2024";
	static	String manufacturer="MEENA FASHION JEWELLERY , MUMBAI-40002";
	static	String asin="B0DJF8LBWQ";
	static	String itemModelNumber="Stylish Pendant Necklace-725";
	static	String countryOfOrigin="India";
	static	String department="womens";
	static	String manufacturerProduct="MEENA FASHION JEWELLERY , MUMBAI-400002, MEENA FASHION JEWELLERY , MUMBAI-40002";
	static	String packer="EENA FASHION JEWELLERY , MUMBAI-400016";
	static	String itemWeight="60 g";
	static	String itemDimensionsLxWxH="50.8 x 3 x 3 Centimeters";
	static	String netQuantity="2 Piece";
	static	String genericName="Pendant Necklaces";
	public static void main(String args[])
	{
		long prize=800L;
		String productDimensions="50.8 x 3 x 3 cm; 50 g";
		String dateFirstAvailable="3 October 2024";
		String manufacturer="MEENA FASHION JEWELLERY , MUMBAI-40002";
		String asin="B0DJF8LBWQ";
		String itemModelNumber="Stylish Pendant Necklace-725";
		String countryOfOrigin="India";
		String department="womens";
		String manufacturerProduct="MEENA FASHION JEWELLERY , MUMBAI-400002, MEENA FASHION JEWELLERY , MUMBAI-40002";
		String packer="EENA FASHION JEWELLERY , MUMBAI-400016";
		String itemWeight="50 g";
		String itemDimensionsLxWxH="50.8 x 3 x 3 Centimeters";
		String netQuantity="1 Piece";
		String genericName="Pendant Necklaces";
		System.out.println("Necklace Prize is is: "+prize);
		System.out.println("Product Dimensions is: "+productDimensions);
		System.out.println("Date First Available is: "+dateFirstAvailable);
		System.out.println("Manufacturer is: "+manufacturer);
		System.out.println("ASIN is: "+asin);
		System.out.println("Item model number is: "+itemModelNumber);
		System.out.println("Country of Origin is: "+countryOfOrigin);
		System.out.println("Department is: "+department);
		System.out.println("Manufacturer Product is: "+manufacturerProduct);
		System.out.println("Packer is: "+packer);
		System.out.println("Item Weight is: "+itemWeight);
		System.out.println("Item Dimensions LxWxH is: "+itemDimensionsLxWxH);
		System.out.println("Net Quantity is: "+netQuantity);
		System.out.println("Generic Name is: "+genericName);
		System.out.println("Necklace Prize is is: "+prize);
		System.out.println("Product Dimensions is: "+productDimensions);
		System.out.println("Date First Available is: "+dateFirstAvailable);
		System.out.println("Manufacturer is: "+manufacturer);
		System.out.println("ASIN is: "+asin);
		System.out.println("Item model number is: "+itemModelNumber);
		System.out.println("Country of Origin is: "+countryOfOrigin);
		System.out.println("Department is: "+department);
		System.out.println("Manufacturer Product is: "+manufacturerProduct);
		System.out.println("Packer is: "+packer);
		System.out.println("Item Weight is: "+itemWeight);
		System.out.println("Item Dimensions LxWxH is: "+itemDimensionsLxWxH);
		System.out.println("Net Quantity is: "+netQuantity);
		System.out.println("Generic Name is: "+genericName);
		System.out.println("-------------------------------------");
		System.out.println("Necklace Prize is is: "+Necklace.prize);
		System.out.println("Product Dimensions is: "+Necklace.productDimensions);
		System.out.println("Date First Available is: "+Necklace.dateFirstAvailable);
		System.out.println("Manufacturer is: "+Necklace.manufacturer);
		System.out.println("ASIN is: "+Necklace.asin);
		System.out.println("Item model number is: "+Necklace.itemModelNumber);
		System.out.println("Country of Origin is: "+Necklace.countryOfOrigin);
		System.out.println("Department is: "+Necklace.department);
		System.out.println("Manufacturer Product is: "+manufacturerProduct);
		System.out.println("Packer is: "+packer);
		System.out.println("Item Weight is: "+itemWeight);
		System.out.println("Item Dimensions LxWxH is: "+itemDimensionsLxWxH);
		System.out.println("Net Quantity is: "+netQuantity);
		System.out.println("Generic Name is: "+genericName);
		System.out.println("Necklace Prize is is: "+Necklace.prize);
		System.out.println("Product Dimensions is: "+Necklace.productDimensions);
		System.out.println("Date First Available is: "+Necklace.dateFirstAvailable);
		System.out.println("Manufacturer is: "+Necklace.manufacturer);
		System.out.println("ASIN is: "+Necklace.asin);
		System.out.println("Item model number is: "+Necklace.itemModelNumber);
		System.out.println("Country of Origin is: "+Necklace.countryOfOrigin);
		System.out.println("Department is: "+Necklace.department);
		System.out.println("Manufacturer Product is: "+Necklace.manufacturerProduct);
		System.out.println("Packer is: "+Necklace.packer);
		System.out.println("Item Weight is: "+Necklace.itemWeight);
		System.out.println("Item Dimensions LxWxH is: "+Necklace.itemDimensionsLxWxH);
		System.out.println("Net Quantity is: "+Necklace.netQuantity);
		System.out.println("Generic Name is: "+Necklace.genericName);
	}
}