class Stationary
{
	static long prize=4299L;
	static	String manufacturer="THREE SIXTY the leather life";
	static	String brand="THREE SIXTY the leather life";
	static	String itemModelNumber="DA5804TP";
	static	String colour="TAUPE";
	static	String closure="Hindustan Foam";
	static	String material="Leather";
	static	String productDimensions="32L x 23W x 4H Centimeters";
	static	String style="Classic";
	static	String size="Hindustan Foam";
	static	String shape="Rectangle";
	static	String countryOfOrigin="India";
	static	String asin="B0FRFX3K5X";
	static	String recommendedUsesForProduct;
	static	String numberOfItems="1";
	static	String productCareInstructions="Avoid exposing the item to extreme temperatures, damp conditions, and direct sunlight., Clean spills immediately with a dry cloth., Occasionally apply leather cream or oils to condition the leather and improve its life.";
	public static void main(String args[])
	{
		long prize=2890L;
		String manufacturer="THREE SIXTY the leather life";
		String brand="THREE SIXTY the leather life";
		String itemModelNumber="DA5804TP";
		String colour="TAUPE";
		String closure="Hindustan Foam";
		String material="Leather";
		String productDimensions="32L x 23W x 4H Centimeters";
		String style="Classic";
		String size="Hindustan Foam";
		String shape="Rectangle";
		String countryOfOrigin="India";
		String asin="B0FRFX3K5X";
		String recommendedUsesForProduct="Document";
		String numberOfItems="1";
		productCareInstructions="Avoid exposing the item to extreme temperatures, damp conditions, and direct sunlight., Clean spills immediately with a dry cloth., Occasionally apply leather cream or oils to condition the leather and improve its life.";
		System.out.println("Leather Valet Tray Prize is: "+prize);
		System.out.println("Manufacturer is: "+manufacturer);
		System.out.println("Brand is: "+brand);
		System.out.println("Item Model Number is: "+itemModelNumber);
		System.out.println("Colour is: "+colour);
		System.out.println("Closure is: "+closure);
		System.out.println("Material is: "+material);
		System.out.println("Product Dimensions is: "+productDimensions);
		System.out.println("Style is: "+style);
		System.out.println("Size is: "+size);
		System.out.println("Shape is: "+shape);
		System.out.println("asin is: "+asin);
		System.out.println("recommendedUsesForProduct is: "+recommendedUsesForProduct);
		System.out.println("numberOfItems is: "+numberOfItems);
		System.out.println("productCareInstructions is: "+productCareInstructions);
		System.out.println("Country of Origin is: "+countryOfOrigin);
		System.out.println("-------------------------------------");
		System.out.println("Leather Valet Tray Prize is: "+Stationary.prize);
		System.out.println("Manufacturer is: "+Stationary.manufacturer);
		System.out.println("Brand is: "+Stationary.brand);
		System.out.println("Item Model Number is: "+Stationary.itemModelNumber);
		System.out.println("Colour is: "+Stationary.colour);
		System.out.println("Closure is: "+Stationary.closure);
		System.out.println("Material is: "+material);
		System.out.println("Product Dimensions is: "+Stationary.productDimensions);
		System.out.println("Style is: "+Stationary.style);
		System.out.println("Size is: "+Stationary.size);
		System.out.println("Shape is: "+Stationary.shape);
		System.out.println("asin is: "+Stationary.asin);
		System.out.println("recommendedUsesForProduct is: "+Stationary.recommendedUsesForProduct);
		System.out.println("numberOfItems is: "+Stationary.numberOfItems);
		System.out.println("productCareInstructions is: "+Stationary.productCareInstructions);
		System.out.println("Country of Origin is: "+Stationary.countryOfOrigin);
	}
}
