class AmazonPrime
{
	public static void main(String args[])
	{
		String tvShows[]={"Farzi"," The Family Man","Mirzzapur","Panchayat","Paatal Lok","From","F.R.I.E.N.D.S","Suzhal- The Vortex",
		"Aspirants","The Boys","Reacher","Mumbai Diaries","Flames","Fallout","The Big Bang Theory","Made In Heaven","Hostel Daze",
		"Bandish Bandits","Young Sheldon","The Forgotten Army-Azaadi Ke Liye","The Night Manager","Immature",
		"Vadhandhi:The Fable of Velonie","Inside Edge","Supernatural","Happy Family Conditions Apply","The Originals","Marry My Husband",
		"The Mentalist","The Good Doctor"};
		System.out.println("TV Shows In Amazon Prime are: );
		String Farzi=tvShows[0];
		System.out.println(Farzi);
		String TheFamilyMan=tvShows[1];
		System.out.println(TheFamilyMan);
		String Mirzzapur=tvShows[2];
		System.out.println(Mirzzapur);
		String Panchayat=tvShows[3];
		System.out.println(Panchayat);
		String PaatalLok=tvShows[4];
		System.out.println(PaatalLok);
		String From=tvShows[5];
		System.out.println(From);
		String FRIENDS=tvShows[6];
		System.out.println(FRIENDS);
		String SuzhalTheVortex=tvShows[7];
		System.out.println(SuzhalTheVortex);
		String Aspirants=tvShows[8];
		System.out.println(Aspirants);
		String TheBoys=tvShows[9];
		System.out.println(TheBoys);
		String Reacher=tvShows[10];
		System.out.println(Reacher);
		String MumbaiDiaries=tvShows[11];
		System.out.println(MumbaiDiaries);
		String Flames=tvShows[12];
		System.out.println(Flames);
		String Fallout=tvShows[13];
		System.out.println(Fallout);
		String TheBigBangTheory=tvShows[14];
		System.out.println(TheBigBangTheory);
		String MadeInHeaven=tvShows[15];
		System.out.println(MadeInHeaven);
		String HostelDaze=tvShows[16];
		System.out.println(HostelDaze);
		String BandishBandits=tvShows[17];
		System.out.println(BandishBandits);
		String YoungSheldo=tvShows[18];
		System.out.println(YoungSheldo);
		String ForgottenArmyAzaadiKeLiye=tvShows[19];
		System.out.println(ForgottenArmyAzaadiKeLiye);
		String TheNightManager=tvShows[20];
		System.out.println(TheNightManager);
		String Immature=tvShows[21];
		System.out.println(Immature);
		String VadhandhiTheFableofVelonie=tvShows[22];
		System.out.println(VadhandhiTheFableofVelonie);
		String InsideEdge=tvShows[23];
		System.out.println(InsideEdge);
		String Supernatural=tvShows[24];
		System.out.println(Supernatural);
		String HappyFamilyConditionsApply=tvShows[25];
		System.out.println(HappyFamilyConditionsApply);
		String TheOriginals=tvShows[26];
		System.out.println(TheOriginals);
		String MarryMyHusband=tvShows[27];
		System.out.println(MarryMyHusband);
		String TheMentalist=tvShows[28];
		System.out.println(TheMentalist);
		String TheGoodDoctor=tvShows[29];
		System.out.println(TheGoodDoctor);
		System.out.println("------------------------------------");
		
		String mysteryAndThrillerTVShow[]={"Daldal","Stea","Cross","InspectorRishi","Dahaad","Dhootha","The Night Manager","Khauf",
		"Breathe","The Girlfriend","Spine VS Everyone","Breathe: Into The Shadows","Celebrity Hunted: italy","Cruel Intentions",
		"Tom Clancy's Jack Ryan","The Walking Dead: The Ones Who Live","The Walking Dead: Dead City","Newtopia","Pretty Little Liars",
		"Poacher","The Man In The High Castle","Arabia Kadali","The 100","Mouse","Under The Dome","Malice","The Alibi","Arrow","Hush Hush","Inland"};
		System.out.println("mystery And ThrillerTVShow In Amazon Prime are: );
		String Daldal=mysteryAndThrillerTVShow[0];
		System.out.println(Daldal);
		String Stea=mysteryAndThrillerTVShow[1];
		System.out.println(Stea);
		String Cross=mysteryAndThrillerTVShow[2];
		System.out.println(Cross);
		String InspectorRishi=mysteryAndThrillerTVShow[3];
		System.out.println(InspectorRishi);
		String Dahaad=mysteryAndThrillerTVShow[4];
		System.out.println(Dahaad);
		String Dhootha=mysteryAndThrillerTVShow[5];
		System.out.println(Dhootha);
		String TheNightManager=mysteryAndThrillerTVShow[6];
		System.out.println(TheNightManager);
		String Khauf=mysteryAndThrillerTVShow[7];
		System.out.println(Khauf);
		String Breathe=mysteryAndThrillerTVShow[8];
		System.out.println(Breathe);
		String TheGirlfriend=mysteryAndThrillerTVShow[9];
		System.out.println(TheGirlfriend);
		String SpineVSEveryone=mysteryAndThrillerTVShow[10];
		System.out.println(SpineVSEveryone);
		String BreatheIntoTheShadows=mysteryAndThrillerTVShow[11];
		System.out.println(BreatheIntoTheShadows);
		String CelebrityHunteditaly=mysteryAndThrillerTVShow[12];
		System.out.println(CelebrityHunteditaly);
		String CruelIntentions=mysteryAndThrillerTVShow[13];
		System.out.println(CruelIntentions);
		String TomClancysJackRyan=mysteryAndThrillerTVShow[14];
		System.out.println(TomClancysJackRyan);
		String TheWalkingDeadTheOnesWhoLive=mysteryAndThrillerTVShow[15];
		System.out.println(TheWalkingDeadTheOnesWhoLive);
		String TheWalkingDeadDeadCity=mysteryAndThrillerTVShow[16];
		System.out.println(TheWalkingDeadDeadCity);
		String Newtopia=mysteryAndThrillerTVShow[17];
		System.out.println(Newtopia);
		String PrettyLittleLiars=mysteryAndThrillerTVShow[18];
		System.out.println(PrettyLittleLiars);
		String Poacher=mysteryAndThrillerTVShow[19];
		System.out.println(Poacher);
		String TheManInTheHighCastle=mysteryAndThrillerTVShow[20];
		System.out.println(TheManInTheHighCastle);
		String ArabiaKadali=mysteryAndThrillerTVShow[21];
		System.out.println(ArabiaKadali);
		String The100=mysteryAndThrillerTVShow[22];
		System.out.println(The100);
		String Mouse=mysteryAndThrillerTVShow[23];
		System.out.println(Mouse);
		String UnderTheDome=mysteryAndThrillerTVShow[24];
		System.out.println(UnderTheDome);
		String Malice=mysteryAndThrillerTVShow[25];
		System.out.println(Malice);
		String TheAlibi=mysteryAndThrillerTVShow[26];
		System.out.println(TheAlibi);
		String Arrow=mysteryAndThrillerTVShow[27];
		System.out.println(Arrow);
		String HushHush=mysteryAndThrillerTVShow[28];
		System.out.println(HushHush);
		String Inland=mysteryAndThrillerTVShow[29];
		System.out.println(Inland);
		System.out.println("------------------------------------");
		
		String filmFareAwardWinners[]={"Paatal Lok","Khauf","Call Me Bae","Anagry Young Men","Gram Chikitsalay","Dupahiya","Bandish Bandits","Panchayat",
		"Mirzzapur","The Family Man","Mumbai Diaries","Paatal Lok","Pushpavalli","Dahaad","Jubilee","Cinema Marte Dum Tak","The Forgotten Army",
		"Breathe: Into The Shadows","Beast Games","Cross","Steal","Fallout","Four More Shots Please!","The Darwin Incident","Sandeep Bhaiya","NCIS",
		"Fallout","Bandwalle","MrBeast:Extreme Survival","The Mighty Nein"};
		System.out.println("FilmFare Award Winners In Amazon Prime are: );
		String PaatalLok=filmFareAwardWinners[0];
		System.out.println(PaatalLok);
		String Khauf=filmFareAwardWinners[1];
		System.out.println(Khauf);
		String CallMeBae=filmFareAwardWinners[2];
		System.out.println(CallMeBae);
		String AnagryYoungMen=filmFareAwardWinners[3];
		System.out.println(AnagryYoungMen);
		String GramChikitsalay=filmFareAwardWinners[4];
		System.out.println(GramChikitsalay);
		String Dupahiya=filmFareAwardWinners[5];
		System.out.println(Dupahiya);
		String BandishBandits=filmFareAwardWinners[6];
		System.out.println(BandishBandits);
		String Panchayat=filmFareAwardWinners[7];
		System.out.println(Panchayat);
		String Mirzzapur=filmFareAwardWinners[8];
		System.out.println(Mirzzapur);
		String TheFamilyMan=filmFareAwardWinners[9];
		System.out.println(TheFamilyMan);
		String MumbaiDiaries=filmFareAwardWinners[10];
		System.out.println(MumbaiDiaries);
		String PaatalLok=filmFareAwardWinners[11];
		System.out.println(PaatalLok);
		String Pushpavalli=filmFareAwardWinners[12];
		System.out.println(Pushpavalli);
		String Dahaad=filmFareAwardWinners[13];
		System.out.println(Dahaad);
		String Jubilee=filmFareAwardWinners[14];
		System.out.println(Jubilee);
		String CinemaMarteDumTak=filmFareAwardWinners[15];
		System.out.println(CinemaMarteDumTak);
		String TheForgottenArmy=filmFareAwardWinners[16];
		System.out.println(TheForgottenArmy);
		String BreatheIntoTheShadows=filmFareAwardWinners[17];
		System.out.println(BreatheIntoTheShadows);
		String BeastGames=filmFareAwardWinners[18];
		System.out.println(BeastGames);
		String Cross=filmFareAwardWinners[19];
		System.out.println(Cross);
		String Steal=filmFareAwardWinners[20];
		System.out.println(Steal);
		String Fallout=filmFareAwardWinners[21];
		System.out.println(Fallout);
		String FourMoreShotsPlease=filmFareAwardWinners[22];
		System.out.println(FourMoreShotsPlease);
		String TheDarwinIncident=filmFareAwardWinners[23];
		System.out.println(TheDarwinIncident);
		String SandeepBhaiya=filmFareAwardWinners[24];
		System.out.println(SandeepBhaiya);
		String NCIS=filmFareAwardWinners[25];
		System.out.println(NCIS);
		String Bandwalle=filmFareAwardWinners[26];
		System.out.println(Bandwalle);
		String MrBeastExtremeSurvival=filmFareAwardWinners[27];
		System.out.println(MrBeastExtremeSurvival);
		String TheMightyNein=filmFareAwardWinners[28];
		System.out.println(TheMightyNein);
		String Pushpavalli=filmFareAwardWinners[29];
		System.out.println(Pushpavalli);
		System.out.println("------------------------------------");
		
		String animax[]={"Y School Heroes","Grand Blue","Remake Our Life!","The Foolish Angle Dances With The Devil","Suicide Squad Isekai",
		"Mashile: Magic And Muscles","The Vexations of a Shut-in Vampire Princess","Konosuba -God's Blessing On World","Oshi No Ko","Haikyu",
		"Wind Breaker","Kubo Won't Let Me BE Invisible","Fruits Basket","Fena: Priate Princess","My Deer Friend Nokotan","My Love Story With Yamada-Kun At Lv999",
		"Why Raeliana Ended Up At The Duke's Mansion","D.Gray-Man","Witch Watch","Demon Slayer: Kimetsu No Yaiba","Parallel World Pharmacy","Teasing Master Takagi-San",
		"How a Realist Hero Rebuilt The Kingdom","Campfire Cooking In Another World With My Absurd Skill","Black Clover","Fate/Zero","Fullmetal Alchemist-BrotherHood",
		"The Faraway Paladin","Tsukimichi -Moonlit Fantasy","Crimson Ragna"};
		System.out.println("Animax In Amazon Prime are: );
		String YSchoolHeroes=animax[0];
		System.out.println(YSchoolHeroes);
		String GrandBlue=animax[1];
		System.out.println(GrandBlue);
		String RemakeOurLife=animax[2];
		System.out.println(RemakeOurLife);
		String TheFoolishAngleDancesWithTheDevil=animax[3];
		System.out.println(TheFoolishAngleDancesWithTheDevil);
		String SuicideSquadIsekai=animax[4];
		System.out.println(SuicideSquadIsekai);
		String MashileMagicAndMuscles=animax[5];
		System.out.println(MashileMagicAndMuscles);
		String TheVexationsofaShutinVampirePrincess=animax[6];
		System.out.println(TheVexationsofaShutinVampirePrincess);
		String KonosubaGodsBlessingOnWorld=animax[7];
		System.out.println(KonosubaGodsBlessingOnWorld);
		String OshiNoKo=animax[8];
		System.out.println(OshiNoKo);
		String Haikyu=animax[9];
		System.out.println(Haikyu);
		String WindBreaker=animax[10];
		System.out.println(WindBreaker);
		String KuboWontLetMeBEInvisible=animax[11];
		System.out.println(KuboWontLetMeBEInvisible);
		String FruitsBasket=animax[12];
		System.out.println(FruitsBasket);
		String FenaPriatePrincess=animax[13];
		System.out.println(FenaPriatePrincess);
		String MyDeerFriendNokotan=animax[14];
		System.out.println(MyDeerFriendNokotan);
		String MyLoveStoryWithYamadaKunAtLv999=animax[15];
		System.out.println(MyLoveStoryWithYamadaKunAtLv999);
		String WhyRaelianaEndedUpAtTheDukesMansion=animax[16];
		System.out.println(WhyRaelianaEndedUpAtTheDukesMansion);
		String DGrayMan=animax[17];
		System.out.println(DGrayMan);
		String WitchWatch=animax[18];
		System.out.println(WitchWatch);
		String DemonSlayerKimetsuNoYaiba=animax[19];
		System.out.println(DemonSlayerKimetsuNoYaiba);
		String ParallelWorldPharmacy=animax[20];
		System.out.println(ParallelWorldPharmacy);
		String TeasingMasterTakagiSan=animax[21];
		System.out.println(TeasingMasterTakagiSan);
		String HowaRealistHeroRebuiltTheKingdom=animax[22];
		System.out.println(HowaRealistHeroRebuiltTheKingdom);
		String CampfireCookingInAnotherWorldWithMyAbsurdSkill=animax[23];
		System.out.println(CampfireCookingInAnotherWorldWithMyAbsurdSkill);
		String BlackClover=animax[24];
		System.out.println(BlackClover);
		String FateZero=animax[25];
		System.out.println(FateZero);
		String FullmetalAlchemistBrotherHood=animax[26];
		System.out.println(FullmetalAlchemistBrotherHood);
		String TheFarawayPaladin=animax[27];
		System.out.println(TheFarawayPaladin);
		String TsukimichiMoonlitFantasy=animax[28];
		System.out.println(TsukimichiMoonlitFantasy);
		String CrimsonRagna=animax[29];
		System.out.println(CrimsonRagna);
		System.out.println("------------------------------------");
		
		
		String foreignLanguage[]={"El Juego De Las Llaves","S.O.Z:Soliders or Zombies","LOL:LastOne Laughing","Betty La Fea: The Story Continues","Peep Time",
		"Subete a mi Moto","Diablo Guardian","Every Minute Counts","The Legend of El Cid","DOM","El Candidato","Wild And Free","You Are Wanted","Como Sobrevivir Soltero",
		"Ferro","Tokyo Vampire Hotel","Hitoshi Matsumoto Presents Documental","Pan y Circo","Extrano Enemigo","Beat","The Challenge: ETA","September Mornings",
		"The Rings Of Fire","The Wheel Of Time","Legacies","Newtoppia","Mayfair Witches","Carnival Row","The Mighty Nein","Tales of the Walking Dead"};
		System.out.println("foreignLanguage In Amazon Prime are: );
		String ElJuegoDeLasLlaves=foreignLanguage[0];
		System.out.println(YSchElJuegoDeLasLlavesoolHeroes);
		String SOZSolidersorZombies=foreignLanguage[1];
		System.out.println(SOZSolidersorZombies);
		String LOLLastOneLaughing=foreignLanguage[2];
		System.out.println(LOLLastOneLaughing);
		String BettyLaFeaTheStoryContinues=foreignLanguage[3];
		System.out.println(BettyLaFeaTheStoryContinues);
		String PeepTime=foreignLanguage[4];
		System.out.println(PeepTime);
		String SubeteamiMoto=foreignLanguage[4];
		System.out.println(SubeteamiMoto);
		String DiabloGuardian=foreignLanguage[6];
		System.out.println(DiabloGuardian);
		String EveryMinuteCounts=foreignLanguage[7];
		System.out.println(EveryMinuteCounts);
		String TheLegendofElCid=foreignLanguage[8];
		System.out.println(TheLegendofElCid);
		String DOM=foreignLanguage[9];
		System.out.println(DOM);
		String ElCandidato=foreignLanguage[10];
		System.out.println(ElCandidato);
		String WildAndFree=foreignLanguage[11];
		System.out.println(WildAndFree);
		String YouAreWanted=foreignLanguage[12];
		System.out.println(YouAreWanted);
		String ComoSobrevivirSoltero=foreignLanguage[13];
		System.out.println(ComoSobrevivirSoltero);
		String Ferro=foreignLanguage[14];
		System.out.println(Ferro);
		String TokyoVampireHotel=foreignLanguage[15];
		System.out.println(TokyoVampireHotel);
		String HitoshiMatsumotoPresentsDocumental=foreignLanguage[16];
		System.out.println(HitoshiMatsumotoPresentsDocumental);
		String PanyCirco=foreignLanguage[17];
		System.out.println(PanyCirco);
		String ExtranoEnemigo=foreignLanguage[18];
		System.out.println(ExtranoEnemigo);
		String Beat=foreignLanguage[19];
		System.out.println(Beat);
		String TheChallengeETA=foreignLanguage[20];
		System.out.println(TheChallengeETA);
		String SeptemberMornings=foreignLanguage[21];
		System.out.println(SeptemberMornings);
		String TheRingsOfFire=foreignLanguage[22];
		System.out.println(TheRingsOfFire);
		String TheWheelOfTime=foreignLanguage[23];
		System.out.println(TheWheelOfTime);
		String Legacies=foreignLanguage[24];
		System.out.println(Legacies);
		String Newtoppia=foreignLanguage[25];
		System.out.println(Newtoppia);
		String MayfairWitches=foreignLanguage[26];
		System.out.println(MayfairWitches);
		String CarnivalRow=foreignLanguage[27];
		System.out.println(CarnivalRow);
		String TheMightyNein=foreignLanguage[28];
		System.out.println(TheMightyNein);
		String Campfire Cooking In Another World With My Absurd Skill=foreignLanguage[29];
		System.out.println(TalesoftheWalkingDead);
		System.out.println("------------------------------------");
		
		String documentaryMovies[]={"Warfare","Tukaram","Farzand","Flight/Risk","WOMB-Women of My Billion","The Blue Angles","Simple Plan: The Kids in the Crowd",
		"Los TIgers Del Norte: Stories to Tell","Lee Soo Man:King of K-Pop","Finding Harmony: A King's Vision","Chirsty","Laura Pausini=Pleasure to Meet you",
		"Zero Se Restart","Mind Games - The Experiment","OPeration Hope-The Children Lost in the Amazon","Girl You Know It's True","Federer: Twelve Final Days",
		"Zara Larsson-Up Close","My Name is Pauli Murray","Unsrapped: The Story of Lil baby","Generation Wealth","Kids Are Growing Up: a Story About A Kid Named Laroi",
		"Frida","The Boy From Medellin","City of Ghosts","I Am: Celine Dion"};
		System.out.println("documentaryMovies In Amazon Prime are: ");
		System.out.println("documentaryMovies In Amazon Prime are: );
		String Warfare=documentaryMovies[0];
		System.out.println(Warfare);Sav\e\
		String Tukaram=documentaryMovies[1];
		System.out.println(Tukaram);
		String FlightRisk=documentaryMovies[2];
		System.out.println(FlightRisk);
		String WOMBWomenofMyBillion=documentaryMovies[3];
		System.out.println(WOMBWomenofMyBillion);
		String TheBlueAngles=documentaryMovies[4];
		System.out.println(TheBlueAngles);
		String SimplePlanTheKidsintheCrowd=documentaryMovies[5];
		System.out.println(SimplePlanTheKidsintheCrowd);
		String LosTIgersDelNorte=documentaryMovies[6];
		System.out.println(LosTIgersDelNorte);
		String KonosubaGodsBlessingOnWorld=documentaryMovies[7];
		System.out.println(KonosubaGodsBlessingOnWorld);
		String OshiNoKo=documentaryMovies[8];
		System.out.println(OshiNoKo);
		String Haikyu=documentaryMovies[9];
		System.out.println(Haikyu);
		String WindBreaker=documentaryMovies[10];
		System.out.println(WindBreaker);
		String KuboWontLetMeBEInvisible=documentaryMovies[11];
		System.out.println(KuboWontLetMeBEInvisible);
		String FruitsBasket=documentaryMovies[12];
		System.out.println(FruitsBasket);
		String FenaPriatePrincess=documentaryMovies[13];
		System.out.println(FenaPriatePrincess);
		String MyDeerFriendNokotan=documentaryMovies[14];
		System.out.println(MyDeerFriendNokotan);
		String MyLoveStoryWithYamadaKunAtLv999=documentaryMovies[15];
		System.out.println(MyLoveStoryWithYamadaKunAtLv999);
		String WhyRaelianaEndedUpAtTheDukesMansion=documentaryMovies[16];
		System.out.println(WhyRaelianaEndedUpAtTheDukesMansion);
		String DGrayMan=documentaryMovies[17];
		System.out.println(DGrayMan);
		String WitchWatch=documentaryMovies[18];
		System.out.println(WitchWatch);
		String DemonSlayerKimetsuNoYaiba=documentaryMovies[19];
		System.out.println(DemonSlayerKimetsuNoYaiba);
		String ParallelWorldPharmacy=documentaryMovies[20];
		System.out.println(ParallelWorldPharmacy);
		String TeasingMasterTakagiSan=documentaryMovies[21];
		System.out.println(TeasingMasterTakagiSan);
		String HowaRealistHeroRebuiltTheKingdom=documentaryMovies[22];
		System.out.println(HowaRealistHeroRebuiltTheKingdom);
		String CampfireCookingInAnotherWorldWithMyAbsurdSkill=documentaryMovies[23];
		System.out.println(CampfireCookingInAnotherWorldWithMyAbsurdSkill);
		String BlackClover=documentaryMovies[24];
		System.out.println(BlackClover);
		String FateZero=documentaryMovies[25];
		System.out.println(FateZero);
		String FullmetalAlchemistBrotherHood=documentaryMovies[26];
		System.out.println(FullmetalAlchemistBrotherHood);
		String TheFarawayPaladin=documentaryMovies[27];
		System.out.println(TheFarawayPaladin);
		String TsukimichiMoonlitFantasy=documentaryMovies[28];
		System.out.println(TsukimichiMoonlitFantasy);
		String CrimsonRagna=documentaryMovies[29];
		System.out.println(CrimsonRagna);
		System.out.println("------------------------------------");
		
		
	}
}