class JioHotstar
{
	public static void main(String args[])
	{
		String liveBusinessNews[]={"CNBC TV18","CNBC-TV18Prime","CNBC Awaaz","CNBC Bajar","News 18 India","News18 MP Chattisgarh",
		"News18 Rajasthan","News18 Tamil Nadu","News18 Marathi","News18 UP Uttarakhand","CNN News18","CNBC-TV18 prime","News18 Kerala",
		"News18 Bangla","News18 Gujurati","News18 Odia","News18 Assam NE","News18 Punjab Haryana","News18 Assam NE","News18 JKLH",
		"CNBC Bajar","CNBC 18","Public TV","Power TV","TV9","Suvarns News","Aaj Tak","ABP News","Bharat24","DD News","India News","NDTV India"};
		System.out.println("live BusinessNews In Jio Hotstar are: ");
		String cNBCTV18=liveBusinessNews[0];
		System.out.println(cNBCTV18);
		String cNBCTV18Prime=liveBusinessNews[1];
		System.out.println(cNBCTV18Prime);
		String cNBCAwaaz=liveBusinessNews[2];
		System.out.println(cNBCAwaaz);
		String cNBCBajar=liveBusinessNews[3];
		System.out.println(cNBCBajar);
		String news18India=liveBusinessNews[4];
		System.out.println(news18India);
		String news18MPChattisgarh=liveBusinessNews[5];
		System.out.println(news18MPChattisgarh);
		String news18Rajasthan=liveBusinessNews[6];
		System.out.println(news18Rajasthan);
		String news18TamilNadu=liveBusinessNews[7];
		System.out.println(news18TamilNadu);
		String news18Marathi=liveBusinessNews[8];
		System.out.println(news18Marathi);
		String news18UPUttarakhand=liveBusinessNews[9];
		System.out.println(news18UPUttarakhand);
		String cNNNews18prime=liveBusinessNews[10];
		System.out.println(cNNNews18prime);
		String news18Kerala=liveBusinessNews[11];
		System.out.println(news18Kerala);
		String news18Bangla=liveBusinessNews[12];
		System.out.println(news18Bangla);
		String news18Gujurati=liveBusinessNews[13];
		System.out.println(news18Gujurati);
		String news18Odia=liveBusinessNews[14];
		System.out.println(news18Odia);
		String news18AssamNE=liveBusinessNews[15];
		System.out.println(news18AssamNE);
		String news18PunjabHaryana=liveBusinessNews[16];
		System.out.println(news18PunjabHaryana);
		String news18JKLH=liveBusinessNews[17];
		System.out.println(news18JKLH);
		String cnbcBajar=liveBusinessNews[18];
		System.out.println(cnbcBajar);
		String cNBC18=liveBusinessNews[19];
		System.out.println(cNBC18);
		String publicTV=liveBusinessNews[20];
		System.out.println(publicTV);
		String powerTV=liveBusinessNews[21];
		System.out.println(powerTV);
		String tV9=liveBusinessNews[22];
		System.out.println(tV9);
		String suvarnsNews=liveBusinessNews[23];
		System.out.println(suvarnsNews);
		String aajTak=liveBusinessNews[24];
		System.out.println(aajTak);
		String aBPNews=liveBusinessNews[25];
		System.out.println(aBPNews);
		String bharat24=liveBusinessNews[26];
		System.out.println(bharat24);
		String dDNews=liveBusinessNews[27];
		System.out.println(dDNews);
		String indiaNews=liveBusinessNews[28];
		System.out.println(indiaNews);
		String nDTVIndia=liveBusinessNews[29];
		System.out.println(nDTVIndia);
		System.out.println("------------------------------------");
		
		String crimeMovies[]={"Police Police","Robinhood","Mrs.Deshpande","Joe Pickett","Cricket Justice","Murderbaad","Bloody Daddy",
		"Search","Siren","Ronth","Thudarum","Kannur Squad","Sholay","Aakhri Sach","Apurva","Vikranth Rona","Heaven","Quiet Plachikkavu",
		"Kerala Crime Files","Vikram Vedha","Monster","Khiladi","Commander Karan Saxena","Goodluck Jerry","Under Salt Marsh","Sanak",
		"Sembi","Fast & Furious9","Aarya"};
		System.out.println("crime Movies In Jio Hotstar are: ");
		String policePolice=crimeMovies[0];
		System.out.println(policePolice);
		String robinhood=crimeMovies[1];
		System.out.println(robinhood);
		String mrsDeshpande=crimeMovies[2];
		System.out.println(mrsDeshpande);
		String joePickett=crimeMovies[3];
		System.out.println(joePickett);
		String cricketJustice=crimeMovies[4];
		System.out.println(cricketJustice);
		String murderbaad=crimeMovies[5];
		System.out.println(murderbaad);
		String bloodyDaddy=crimeMovies[6];
		System.out.println(bloodyDaddy);
		String search=crimeMovies[7];
		System.out.println(search);
		String siren=crimeMovies[8];
		System.out.println(siren);
		String ronth=crimeMovies[9];
		System.out.println(ronth);
		String thudarum=crimeMovies[10];
		System.out.println(thudarum);
		String kannurSquad=crimeMovies[11];
		System.out.println(kannurSquad);
		String sholay=crimeMovies[12];
		System.out.println(sholay);
		String aakhriSach=crimeMovies[13];
		System.out.println(aakhriSach);
		String apurva=crimeMovies[14];
		System.out.println(apurva);
		String vikranthRona=crimeMovies[15];
		System.out.println(vikranthRona);
		String heaven=crimeMovies[16];
		System.out.println(heaven);
		String quietPlachikkavu=crimeMovies[17];
		System.out.println(quietPlachikkavu);
		String keralaCrimeFiles=crimeMovies[18];
		System.out.println(keralaCrimeFiles);
		String vikramVedha=crimeMovies[19];
		System.out.println(vikramVedha);
		String monster=crimeMovies[20];
		System.out.println(monster);
		String khiladi=crimeMovies[21];
		System.out.println(khiladi);
		String commanderKaranSaxena=crimeMovies[22];
		System.out.println(commanderKaranSaxena);
		String goodluckJerry=crimeMovies[23];
		System.out.println(goodluckJerry);
		String aajtak=crimeMovies[24];
		System.out.println(aajtak);
		String underSaltMarsh=crimeMovies[25];
		System.out.println(underSaltMarsh);
		String sembi=crimeMovies[26];
		System.out.println(sembi);
		String fastFurious9=crimeMovies[27];
		System.out.println(fastFurious9);
		String aarya=crimeMovies[28];
		System.out.println(aarya);
		String ndtvIndia=crimeMovies[29];
		System.out.println(ndtvIndia);
		System.out.println("------------------------------------");
		
		
		String  thrillMovies[]={"Mermaid Down","Raid","Kaabil","The Grey","Airlift","Villain","KEE","Maatr","Maayavan","Laal Rang",
		"AAkhiri Chaal","I Spit on your Grave","Welcome Home","Ugly","The Thieves","I See You","D-16","8 Thottakkal","Monsoon Shootout",
		"Security","Dongri Ka Raja","Omerta","COPY","Jaal Ek Tantra","Khatron Se Khelenge","Bad Samaritan","Mirchi Malin","Between Words",
		"Hate Story 2","Belzebuth"};
		System.out.println("thrill Movies In Jio Hotstar are: ");
		String mermaidDown=thrillMovies[1];
		System.out.println(mermaidDown);
		String raid=thrillMovies[2];
		System.out.println(raid);
		String kaabil=thrillMovies[3];
		System.out.println(kaabil);
		String theGrey=thrillMovies[4];
		System.out.println(theGrey);
		String airlift=thrillMovies[5];
		System.out.println(airlift);
		String villain=thrillMovies[6];
		System.out.println(villain);
		String kEE=thrillMovies[7];
		System.out.println(kEE);
		String maatr=thrillMovies[8];
		System.out.println(maatr);
		String maayavan=thrillMovies[9];
		System.out.println(maayavan);
		String laalRang=thrillMovies[10];
		System.out.println(laalRang);
		String aAkhiriChaal=thrillMovies[11];
		System.out.println(aAkhiriChaal);
		String ispitonyourGrave=thrillMovies[12];
		System.out.println(ispitonyourGrave);
		String cOPY=thrillMovies[13];
		System.out.println(cOPY);
		String hateStory2=thrillMovies[14];
		System.out.println(hateStory2);
		String newsAssamNE=thrillMovies[15];
		System.out.println(newsAssamNE);
		String newsPunjabHaryana=thrillMovies[16];
		System.out.println(newsPunjabHaryana);
		String newsJKLH=thrillMovies[17];
		System.out.println(newsJKLH);
		String cnbcbajar=thrillMovies[18];
		System.out.println(cnbcbajar);
		String cnbc18=thrillMovies[19];
		System.out.println(cnbc18);
		String publictv=thrillMovies[20];
		System.out.println(publictv);
		String powertv=thrillMovies[21];
		System.out.println(powertv);
		String tv9=thrillMovies[22];
		System.out.println(tv9);
		String suvarnaNews=thrillMovies[23];
		System.out.println(suvarnaNews);
		String aajtakh=thrillMovies[24];
		System.out.println(aajtakh);
		String abpnews=thrillMovies[25];
		System.out.println(abpnews);
		String bharath24=thrillMovies[26];
		System.out.println(bharath24);
		String ddNews=thrillMovies[27];
		System.out.println(ddNews);
		String indianews=thrillMovies[28];
		System.out.println(indianews);
		String ndtvindia=thrillMovies[29];
		System.out.println(ndtvindia);
		
		String devilsMovie[]={"Shootout At Lokhandwala","The descent","Karz","Jeepers 2","Garv","Krishna Cottage","lajja","The Descent part2",
		"Aan","Bhoot","Deewangee","The Stoneman","Shutter","Dawn of the Dead","13 B","Inside Man","Ring","Bourne Identity","Chandramukhi",
		"Live Free or Die hard","1920 Gayatri","Changeling","State of Play","Hannibai","Red Dragon","Untraceble","darna mana","Shikari",
		"Sikandar","Kucch To Hai","88 Minutes"};
		System.out.println("devils Movie In Jio Hotstar are: ");
		String shootoutAtLokhandwala=devilsMovie[0];
		System.out.println(shootoutAtLokhandwala);
		String thedescent=devilsMovie[1];
		System.out.println(thedescent);
		String karz=devilsMovie[2];
		System.out.println(karz);
		String jeepers2=devilsMovie[3];
		System.out.println(jeepers2);
		String garv=devilsMovie[4];
		System.out.println(garv);
		String news18mpchattisgarh=devilsMovie[5];
		System.out.println(news18mpchattisgarh);
		String krishnaCottage=devilsMovie[6];
		System.out.println(krishnaCottage);
		String lajja=devilsMovie[7];
		System.out.println(lajja);
		String theDescentpart2=devilsMovie[8];
		System.out.println(theDescentpart2);
		String aan=devilsMovie[9];
		System.out.println(aan);
		String bhoot=devilsMovie[10];
		System.out.println(bhoot);
		String Deewangee=devilsMovie[11];
		System.out.println(Deewangee);
		String TheStoneman=devilsMovie[12];
		System.out.println(TheStoneman);
		String Shutter=devilsMovie[13];
		System.out.println(Shutter);
		String DawnoftheDead=devilsMovie[14];
		System.out.println(DawnoftheDead);
		System.out.println("------------------------------------");
		
		
		String mcuTimeline[]={"Eyes of Wakanda","Captain America","Captain Marvel","Iron Man","Iron Man 2","Thor","Avengers","Thor",
		"Iron Man 3","Captain America","Guardians of the Galaxy","Guardians of the Galaxy 2","I am Groot","Daredevil","Jessica Jones",
		"Ant-Man","Iron Fist","Defenders","Civil War","Black Widow","Black Panther","Punisher","Doctor Strange","Thor Rahnarok","Echo",
		"Thor Love and Thander","Agatha all Along","The Guardians of the Galaxy 2","Deadpool & Wolverine","Thunder Bolts"};
		System.out.println("mcuTimeline In Jio Hotstar are: ");
		String eyesofwakanda=mcuTimeline[0];
		System.out.println(eyesofwakanda);
		String captainamerica=mcuTimeline[1];
		System.out.println(captainamerica);
		String captainmarvel=mcuTimeline[2];
		System.out.println(captainmarvel);
		String ironman=mcuTimeline[3];
		System.out.println(ironman);
		String ironMan2=mcuTimeline[4];
		System.out.println(ironMan2);
		String thor=mcuTimeline[5];
		System.out.println(thor);
		String avengers=mcuTimeline[6];
		System.out.println(avengers);
		String ironMan3=mcuTimeline[7];
		System.out.println(ironMan3);
		String captainAmericans=mcuTimeline[8];
		System.out.println(captainAmericans);
		String guardiansoftheGalaxy=mcuTimeline[9];
		System.out.println(guardiansoftheGalaxy);
		String guardiansoftheGalaxy2=mcuTimeline[10];
		System.out.println(guardiansoftheGalaxy2);
		String iamGroot=mcuTimeline[11];
		System.out.println(iamGroot);
		String daredevil=mcuTimeline[12];
		System.out.println(daredevil);
		String jessicaJones=mcuTimeline[13];
		System.out.println(jessicaJones);
		String antMan=mcuTimeline[14];
		System.out.println(antMan);
		String ironFist=mcuTimeline[15];
		System.out.println(ironFist);
		String defenders=mcuTimeline[16];
		System.out.println(defenders);
		String civilWar=mcuTimeline[17];
		System.out.println(civilWar);
		String blackWidow=mcuTimeline[18];
		System.out.println(blackWidow);
		String blackPanther=mcuTimeline[19];
		System.out.println(blackPanther);
		System.out.println("------------------------------------");
		
		String fairyTales[]={"Tangled","Maleficient","Frozen2","Narnia","THe Princess Diaries","Moana","Frozen","Mulan","Alice in Wonderland",
		"Enchanted","Cinderella","Tinker Bell Neverbeast","The Little Mermaid","Alice","Alladdin","Tinker Bell","Beauty and the Beast",
		"Princess Rrog","Tinker Bell Lost Treasure","Sleeping Beauty","Elena of Avalor","Tangled the Series","Ariel","Hocus Pocus 2","Snow White",
		"The Castle Quest","Pocahontas","Tinker Bell Great fairy Resue","Maleficient Mistress of Evil"};
		System.out.println("fairyTales In Jio Hotstar are: ");
		String tangled=fairyTales[0];
		System.out.println(tangled);
		String maleficient=fairyTales[1];
		System.out.println(maleficient);
		String frozen2=fairyTales[2];
		System.out.println(frozen2);
		String narnia=fairyTales[3];
		System.out.println(narnia);
		String thePrincessDiaries=fairyTales[4];
		System.out.println(thePrincessDiaries);
		String moana=fairyTales[5];
		System.out.println(moana);
		String frozen=fairyTales[6];
		System.out.println(frozen);
		String mulan=fairyTales[7];
		System.out.println(mulan);
		String aliceinWonderland=fairyTales[8];
		System.out.println(aliceinWonderland);
		String enchanted=fairyTales[9];
		System.out.println(enchanted);
		String cinderella=fairyTales[10];
		System.out.println(cinderella);
		String tinkerBellNeverbeast=fairyTales[11];
		System.out.println(tinkerBellNeverbeast);
		String beautyandtheBeast=fairyTales[12];
		System.out.println(beautyandtheBeast);
		String princessRrog=fairyTales[13];
		System.out.println(princessRrog);
		String alladdin=fairyTales[14];
		System.out.println(alladdin);
		String tinkerBell=fairyTales[15];
		System.out.println(tinkerBell);
		String tinkerBellLostTreasure=fairyTales[16];
		System.out.println(tinkerBellLostTreasure);
		String sleepingBeauty=fairyTales[17];
		System.out.println(sleepingBeauty);
		String elenaofAvalor=fairyTales[18];
		System.out.println(elenaofAvalor);
		String tangledtheSeries=fairyTales[19];
		System.out.println(tangledtheSeries);
		System.out.println("------------------------------------");
	}
}