class Netflix
{
	public static void main(String args[])
	{
		String kannadaMovies[]={"Bagheera","Salaar part 1","Kantara","U-turn","Officer On Duty","Shivaji Surathkal",
		"Dia","Operational Gold Fish","Iraivan","Takkar","Garuda Gamana Vrishabha Vahana","KGF Chapter 1",
		"KGF Chapter 2","777Charlie","Aachar & Co","Mayabazar","Gantumotte","Birbal Triogy Case 1","Love Moktail",
		"Hondisi Bareyiri","Trikona","Mooranne Krishnappa","Gandeevadhari Arjuna","Guntur Kaaram","Japan","DSP",
		"Hi Nanna","Rajakumara","Mugaru Male","Vikranth Ronna"};
		System.out.println("Kannada Movies In Netflix are: ");
		String bagheera=kannadaMovies[0];
		System.out.println(bagheera);
		String salaarpart1=kannadaMovies[1];
		System.out.println(salaarpart1);
		String kantara=kannadaMovies[2];
		System.out.println(kantara);
		String uturn=kannadaMovies[3];
		System.out.println(uturn);
		String officerOnDuty=kannadaMovies[4];
		System.out.println(officerOnDuty);
		String shivajiSurathkal=kannadaMovies[5];
		System.out.println(shivajiSurathkal);
		String dia=kannadaMovies[6];
		System.out.println(dia);
		String operationalGoldFish=kannadaMovies[7];
		System.out.println(operationalGoldFish);
		String iraivan=kannadaMovies[8];
		System.out.println(iraivan);
		String takkar=kannadaMovies[9];
		System.out.println(takkar);
		String garudaGamanaVrishabhaVahana=kannadaMovies[10];
		System.out.println(garudaGamanaVrishabhaVahana);
		String kGFChapter1=kannadaMovies[11];
		System.out.println(kGFChapter1);
		String kGFChapter2=kannadaMovies[12];
		System.out.println(kGFChapter2);
		String Charlie=kannadaMovies[13];
		System.out.println(Charlie);
		String AacharCo=kannadaMovies[14];
		System.out.println(AacharCo);
		String Mayabazar=kannadaMovies[15];
		System.out.println(Mayabazar);
		String Gantumotte=kannadaMovies[16];
		System.out.println(Gantumotte);
		String BirbalTriogyCase1=kannadaMovies[17];
		System.out.println(BirbalTriogyCase1);
		String LoveMoktail=kannadaMovies[18];
		System.out.println(LoveMoktail);
		String HondisiBareyiri=kannadaMovies[19];
		System.out.println(HondisiBareyiri);
		String Trikona=kannadaMovies[20];
		System.out.println(Trikona);
		String MooranneKrishnappa=kannadaMovies[21];
		System.out.println(MooranneKrishnappa);
		String GandeevadhariArjuna=kannadaMovies[22];
		System.out.println(GandeevadhariArjuna);
		String GunturKaaram=kannadaMovies[23];
		System.out.println(GunturKaaram);
		String Japan=kannadaMovies[24];
		System.out.println(Japan);
		String DSP=kannadaMovies[25];
		System.out.println(DSP);
		String HiNanna=kannadaMovies[26];
		System.out.println(HiNanna);
		String Rajakumara=kannadaMovies[27];
		System.out.println(Rajakumara);
		String MugaruMale=kannadaMovies[28];
		System.out.println(MugaruMale);
		String VikranthRonna=kannadaMovies[29];
		System.out.println(VikranthRonna);
		System.out.println("------------------------------------");
		
		String hindiIndianMovies[]={"Dhurandhar","Saiyaara","hichki","Jolly LLB3","Haq","Sikandar","War 2",
		"Dangal","Sultan","Kathal-A Jackfruit Mystery","Mahavatr Narasimha","Dhadak 2","Deva",
		"Bhool Bhulaiyaa 3","Gangubai Kathiawadi","Laapataa Ladies","Fighter","Dhoom Dhaam",
		"Yeh Jawanni Hai Deewani","Chhaava","Jaat","Inspector Zende","Badmaash Company","Mission Manju",
		"Crew","Chennai Express","Mujhse Dosti Karoge!","The Diplomat","Tehran","Maa"};
		System.out.println("Hindi Movies In Netflix are: ");
		String Dhurandhar=hindiIndianMovies[0];
		System.out.println(Dhurandhar);
		String Saiyaara=hindiIndianMovies[1];
		System.out.println(Saiyaara);
		String hichki=hindiIndianMovies[2];
		System.out.println(hichki);
		String JollyLLB3=hindiIndianMovies[3];
		System.out.println(JollyLLB3);
		String Haq=hindiIndianMovies[4];
		System.out.println(Haq);
		String Sikandar=hindiIndianMovies[5];
		System.out.println(Sikandar);
		String War2=hindiIndianMovies[6];
		System.out.println(War2);
		String Dangal=hindiIndianMovies[7];
		System.out.println(Dangal);
		String Sultan=hindiIndianMovies[8];
		System.out.println(Sultan);
		String KathalAJackfruitMystery=hindiIndianMovies[9];
		System.out.println(KathalAJackfruitMystery);
		String MahavatrNarasimha=hindiIndianMovies[10];
		System.out.println(MahavatrNarasimha);
		String Dhadak2=hindiIndianMovies[11];
		System.out.println(Dhadak2);
		String Deva=hindiIndianMovies[12];
		System.out.println(Deva);
		String BhoolBhulaiyaa3=hindiIndianMovies[13];
		System.out.println(BhoolBhulaiyaa3);
		String GangubaiKathiawadi=hindiIndianMovies[14];
		System.out.println(GangubaiKathiawadi);
		String LaapataaLadies=hindiIndianMovies[15];
		System.out.println(LaapataaLadies);
		String Fighter=hindiIndianMovies[16];
		System.out.println(Fighter);
		String DhoomDhaam=hindiIndianMovies[17];
		System.out.println(DhoomDhaam);
		String YehJawanniHaiDeewani=hindiIndianMovies[18];
		System.out.println(YehJawanniHaiDeewani);
		String Chhaava=hindiIndianMovies[19];
		System.out.println(Chhaava);
		String Jaat=hindiIndianMovies[20];
		System.out.println(Jaat);
		String InspectorZende=hindiIndianMovies[21];
		System.out.println(InspectorZende);
		String BadmaashCompany=hindiIndianMovies[22];
		System.out.println(BadmaashCompany);
		String MissionManju=hindiIndianMovies[23];
		System.out.println(MissionManju);
		String Crew=hindiIndianMovies[24];
		System.out.println(Crew);
		String ChennaiExpress=hindiIndianMovies[25];
		System.out.println(ChennaiExpress);
		String MujhseDostiKaroge=hindiIndianMovies[26];
		System.out.println(MujhseDostiKaroge);
		String TheDiplomat=hindiIndianMovies[27];
		System.out.println(TheDiplomat);
		String Tehran=hindiIndianMovies[28];
		System.out.println(Tehran);
		String Maa=hindiIndianMovies[29];
		System.out.println(Maa);
		System.out.println("------------------------------------");
		
		String teluguMovies[]={"Telusa Kada","They Call Him OG","Lucky Baskar","Hi Nanna","Guntur Kaaram",
		"Pushpa","Dasara","Devara","Saripodhaa Sanivaaram","RRR","Pushpa 2","Hit 3","Godfather","Waltair Veerayya",
		"Kushi","Bro","Bhola Shankar","Game Over","Mana Shankara Varaprasad Garu","Anaganaga Oka Raju",
		"Sampradayini Suppini Suddapoosani","Nari Nari Naduma Murari","Psych Siddhartha","The Raja Saab",
		"Nilakanta","Champion","Patang","Annagaru Vostaru","Shambhala"};
		System.out.println("Telugu Movies in Netflix are: ");
		String telusaKada=teluguMovies[0];
		System.out.println(telusaKada);
		String theyCallHimOG=teluguMovies[1];
		System.out.println(theyCallHimOG);
		String luckyBaskar=teluguMovies[2];
		System.out.println(luckyBaskar);
		String hiNannas=teluguMovies[3];
		System.out.println(hiNannas);
		String gunturKaaram=teluguMovies[4];
		System.out.println(gunturKaaram);
		String pushpa=teluguMovies[5];
		System.out.println(pushpa);
		String dasara=teluguMovies[6];
		System.out.println(dasara);
		String devara=teluguMovies[7];
		System.out.println(devara);
		String saripodhaa=teluguMovies[8];
		System.out.println(saripodhaa);
		String sanivaaram=teluguMovies[9];
		System.out.println(sanivaaram);
		String rRR=teluguMovies[10];
		System.out.println(rRR);
		String pushpa2=teluguMovies[11];
		System.out.println(pushpa2);
		String hit3=teluguMovies[12];
		System.out.println(hit3);
		String godfather=teluguMovies[13];
		System.out.println(godfather);
		String waltairVeerayya=teluguMovies[14];
		System.out.println(waltairVeerayya);
		String kushi=teluguMovies[15];
		System.out.println(kushi);
		String bro=teluguMovies[16];
		System.out.println(bro);
		String bholaShankar=teluguMovies[17];
		System.out.println(bholaShankar);
		String gameOver=teluguMovies[18];
		System.out.println(gameOver);
		String manaShankaraVaraprasadGaru=teluguMovies[19];
		System.out.println(manaShankaraVaraprasadGaru);
		String anaganagaOkaRaju=teluguMovies[20];
		System.out.println(anaganagaOkaRaju);
		String sampradayiniSuppiniSuddapoosani=teluguMovies[21];
		System.out.println(sampradayiniSuppiniSuddapoosani);
		String nariNariNadumaMurari=teluguMovies[22];
		System.out.println(nariNariNadumaMurari);
		String psychSiddhartha=teluguMovies[23];
		System.out.println(psychSiddhartha);
		String TheRajaSaab=teluguMovies[24];
		System.out.println(TheRajaSaab);
		String Nilakanta=teluguMovies[25];
		System.out.println(Nilakanta);
		String Champion=teluguMovies[26];
		System.out.println(Champion);
		String Patang=teluguMovies[27];
		System.out.println(Patang);
		String AnnagaruVostaru=teluguMovies[28];
		System.out.println(AnnagaruVostaru);
		String shambhala=teluguMovies[29];
		System.out.println(shambhala);
		System.out.println("------------------------------------");
		
		String malayalamMovies[]={"Eko","Kurup","Ullozhukku","Anweshippin Kandethum","Dear Friend","Odum Kuthira Chaadum Kuthira",
		"Kondal","Iratta","Detective Ujjwalan","Irul","Kaapa","Nanpakal Nerathu Mayakkam","Jana Gana Mana","RDX Robert Dony Xavier",
		"Kumari","Nayattu","Minnal Murali","The Teacher","Ayavaashi","Rekha","Vaashi","Attention Please","CBI 5","Padavettu",
		"Thottappan","Vikrithi","Rifle Club","Ariyippu","Pulimada","Maniyarayile Ashokan"};
		System.out.println("Malayalam Movies in Netflix are: ");
		String Eko=malayalamMovies[0];
		System.out.println(Eko);
		String Kurup=malayalamMovies[1];
		System.out.println(Kurup);
		String Ullozhukku=malayalamMovies[2];
		System.out.println(Ullozhukku);
		String AnweshippinKandethum=malayalamMovies[3];
		System.out.println(AnweshippinKandethum);
		String DearFriend=malayalamMovies[4];
		System.out.println(DearFriend);
		String OdumKuthiraChaadumKuthira=malayalamMovies[5];
		System.out.println(OdumKuthiraChaadumKuthira);
		String Kondal=malayalamMovies[6];
		System.out.println(Kondal);
		String Iratta=malayalamMovies[7];
		System.out.println(Iratta);
		String DetectiveUjjwalan=malayalamMovies[8];
		System.out.println(DetectiveUjjwalan);
		String Irul=malayalamMovies[9];
		System.out.println(Irul);
		String Kaapa=malayalamMovies[10];
		System.out.println(Kaapa);
		String NanpakalNerathuMayakkam=malayalamMovies[11];
		System.out.println(NanpakalNerathuMayakkam);
		String JanaGanaMana=malayalamMovies[12];
		System.out.println(JanaGanaMana);
		String RDXRobertDonyXavier=malayalamMovies[13];
		System.out.println(RDXRobertDonyXavier);
		String Kumari=malayalamMovies[14];
		System.out.println(Kumari);
		String Nayattu=malayalamMovies[15];
		System.out.println(Nayattu);
		String MinnalMurali=malayalamMovies[16];
		System.out.println(MinnalMurali);
		String TheTeacher=malayalamMovies[17];
		System.out.println(TheTeacher);
		String Ayavaashi=malayalamMovies[18];
		System.out.println(Ayavaashi);
		String Rekha=malayalamMovies[19];
		System.out.println(Rekha);
		String Vaashi=malayalamMovies[20];
		System.out.println(Vaashi);
		String AttentionPlease=malayalamMovies[21];
		System.out.println(AttentionPlease);
		String CBI5=malayalamMovies[22];
		System.out.println(CBI5);
		String Padavettu=malayalamMovies[23];
		System.out.println(Padavettu);
		String Thottappan=malayalamMovies[24];
		System.out.println(Thottappan);
		String Vikrithi=malayalamMovies[25];
		System.out.println(Vikrithi);
		String RifleClub=malayalamMovies[26];
		System.out.println(RifleClub);
		String Ariyippu=malayalamMovies[27];
		System.out.println(Ariyippu);
		String Pulimada=malayalamMovies[28];
		System.out.println(Pulimada);
		String ManiyarayileAshokan=malayalamMovies[29];
		System.out.println(ManiyarayileAshokan);
		System.out.println("------------------------------------");
		
		String marathiMovies[]={"Aapla Manus","Baipan Bhari Deva","Ved","Pawankhind","Natsamrat","Katyar Kaljat Ghusali",
		"Thackeray","Anandi Gopal","Ti Saddhya Kay Karte","Chi Va Chi Sau Ka","Killa","Happy Journey","Premachi Gosht",
		"Savita Damodar Paranjpe","kumari","Muramba","nayattu","minnalMurali","theTeacher","ayavaashi","rekha",
		"Fandry","Dr.Kashinath Ghanekar","Court","Deool","Harishchandra's Factory","Choked","Sillu Karupatti","Chola","Jiivi"};
		System.out.println("Marathi Movies in Netflix are: ");
		String AaplaManus=marathiMovies[0];
		System.out.println(AaplaManus);
		String BaipanBhariDeva=marathiMovies[1];
		System.out.println(BaipanBhariDeva);
		String Ved=marathiMovies[2];
		System.out.println(Ved);
		String Pawankhind=marathiMovies[3];
		System.out.println(Pawankhind);
		String Natsamrat=marathiMovies[4];
		System.out.println(Natsamrat);
		String KatyarKaljatGhusali=marathiMovies[5];
		System.out.println(KatyarKaljatGhusali);
		String Thackeray=marathiMovies[6];
		System.out.println(Thackeray);
		String AnandiGopal=marathiMovies[7];
		System.out.println(AnandiGopal);
		String TiSaddhyaKayKarte=marathiMovies[8];
		System.out.println(TiSaddhyaKayKarte);
		String ChiVaChiSauKa=marathiMovies[9];
		System.out.println(ChiVaChiSauKa);
		String Killa=marathiMovies[10];
		System.out.println(Killa);
		String HappyJourney=marathiMovies[11];
		System.out.println(HappyJourney);
		String PremachiGosht=marathiMovies[12];
		System.out.println(PremachiGosht);
		String SavitaDamodarParanjpe=marathiMovies[13];
		System.out.println(SavitaDamodarParanjpe);
		String kumari=marathiMovies[14];
		System.out.println(kumari);
		String nayattu=marathiMovies[15];
		System.out.println(nayattu);
		String minnalMurali=marathiMovies[16];
		System.out.println(minnalMurali);
		String theTeacher=marathiMovies[17];
		System.out.println(theTeacher);
		String ayavaashi=marathiMovies[18];
		System.out.println(ayavaashi);
		String rekha=marathiMovies[19];
		System.out.println(rekha);
		String vaashi=marathiMovies[20];
		System.out.println(vaashi);
		String attentionPlease=marathiMovies[21];
		System.out.println(attentionPlease);
		String cbI5=marathiMovies[22];
		System.out.println(cbI5);
		String padavettu=marathiMovies[23];
		System.out.println(padavettu);
		String thottappan=marathiMovies[24];
		System.out.println(thottappan);
		String vikrithi=marathiMovies[25];
		System.out.println(vikrithi);
		String rifleClub=marathiMovies[26];
		System.out.println(rifleClub);
		String ariyippu=marathiMovies[27];
		System.out.println(ariyippu);
		String pulimada=marathiMovies[28];
		System.out.println(pulimada);
		String maniyarayileAshokan=marathiMovies[29];
		System.out.println(maniyarayileAshokan);
		System.out.println("------------------------------------");
		
		String tamilMovies[]={"Stephan","Aaryan","Kaantha","Dude","Maareesan","Revolver Rita","Bison Kaalamaadan","Thug Life",
		"Good Bad Ugly","Retro","Perusu","Oho Enthan Baby","Psycho","Meiyazhagan","DeAr","Maharaja","Amaran","Dragon","Raangi",
		"The Greatest of All Time","Varalaru Mukkiyam","Vidaamuyarchi","Vaathi","Irugapatru","Beast","Visaranai",
		"Nitham Oru Vaanam","Leo","Hey! Sinamika","Doctor"};
		System.out.println("Tamil Movies in Netflix are: ");
		String Stephan=tamilMovies[0];
		System.out.println(Stephan);
		String Aaryan=tamilMovies[1];
		System.out.println(Aaryan);
		String Kaantha=tamilMovies[2];
		System.out.println(Kaantha);
		String Dude=tamilMovies[3];
		System.out.println(Dude);
		String Maareesan=tamilMovies[4];
		System.out.println(Maareesan);
		String RevolverRita=tamilMovies[5];
		System.out.println(RevolverRita);
		String BisonKaalamaadankeray=tamilMovies[6];
		System.out.println(BisonKaalamaadankeray);
		String ThugLife=tamilMovies[7];
		System.out.println(ThugLife);
		String GoodBadUgly=tamilMovies[8];
		System.out.println(GoodBadUgly);
		String Retro=tamilMovies[9];
		System.out.println(Retro);
		String Perusu=tamilMovies[10];
		System.out.println(Perusu);
		String OhoEnthanBaby=tamilMovies[11];
		System.out.println(OhoEnthanBaby);
		String Psycho=tamilMovies[12];
		System.out.println(Psycho);
		String Meiyazhagan=tamilMovies[13];
		System.out.println(Meiyazhagan);
		String DeAr=tamilMovies[14];
		System.out.println(DeAr);
		String Maharaja=tamilMovies[15];
		System.out.println(Maharaja);
		String Amaran=tamilMovies[16];
		System.out.println(Amaran);
		String Dragon=tamilMovies[17];
		System.out.println(Dragon);
		String Raangi=tamilMovies[18];
		System.out.println(Raangi);
		String TheGreatestofAllTime=tamilMovies[19];
		System.out.println(TheGreatestofAllTime);
		String VaralaruMukkiyam=tamilMovies[20];
		System.out.println(VaralaruMukkiyam);
		String Vidaamuyarchi=tamilMovies[21];
		System.out.println(Vidaamuyarchi);
		String Vaathi=tamilMovies[22];
		System.out.println(Vaathi);
		String Irugapatru=tamilMovies[23];
		System.out.println(Irugapatru);
		String Beast=tamilMovies[24];
		System.out.println(Beast);
		String Visaranai=tamilMovies[25];
		System.out.println(Visaranai);
		String NithamOruVaanam=tamilMovies[26];
		System.out.println(NithamOruVaanam);
		String Leo=tamilMovies[27];
		System.out.println(Leo);
		String HeySinamika=tamilMovies[28];
		System.out.println(HeySinamika);
		String Doctor=tamilMovies[29];
		System.out.println(Doctor);
		System.out.println("------------------------------------");
		
	}
}