class AdithyaBirlaGroupExecutor {
    public static void main(String[] args) {
        AdithyaBirlaGroup abg1 = new AdithyaBirlaGroup(); 
		abg1.groupId=1; 
		abg1.groupName="ABG_Division_1"; 
		abg1.sector="Cement"; 
		abg1.headquarters="Mumbai"; 
		abg1.revenue=10500.0; 
		RCB rcb1=new RCB(); 
		rcb1.teamId=1301; 
		rcb1.teamName="RCB_Squad_1"; 
		rcb1.captain="Captain_1"; 
		rcb1.titles=1;
		rcb1.homeGround="Chinnaswamy Stadium"; 
		abg1.rcb=rcb1; 
		abg1.getGroupDetails();
        AdithyaBirlaGroup abg2 = new AdithyaBirlaGroup(); 
		abg2.groupId=2; 
		abg2.groupName="ABG_Division_2";
		abg2.sector="Telecom"; 
		abg2.headquarters="Mumbai"; 
		abg2.revenue=11000.0; 
		RCB rcb2=new RCB(); 
		rcb2.teamId=1302; 
		rcb2.teamName="RCB_Squad_2"; 
		rcb2.captain="Captain_2"; 
		rcb2.titles=2; 
		rcb2.homeGround="Chinnaswamy Stadium"; 
		abg2.rcb=rcb2; abg2.getGroupDetails();
        AdithyaBirlaGroup abg3 = new AdithyaBirlaGroup(); 
		abg3.groupId=3; 
		abg3.groupName="ABG_Division_3"; 
		abg3.sector="Fashion"; 
		abg3.headquarters="Mumbai"; 
		abg3.revenue=11500.0; 
		RCB rcb3=new RCB(); 
		rcb3.teamId=1303; 
		rcb3.teamName="RCB_Squad_3"; 
		rcb3.captain="Captain_3"; 
		rcb3.titles=0; 
		rcb3.homeGround="Chinnaswamy Stadium"; 
		abg3.rcb=rcb3; 
		abg3.getGroupDetails();
        AdithyaBirlaGroup abg4 = new AdithyaBirlaGroup(); 
		abg4.groupId=4; 
		abg4.groupName="ABG_Division_4"; 
		abg4.sector="Finance"; 
		abg4.headquarters="Mumbai"; 
		abg4.revenue=12000.0; 
		RCB rcb4=new RCB(); 
		rcb4.teamId=1304; 
		rcb4.teamName="RCB_Squad_4"; 
		rcb4.captain="Captain_4"; 
		rcb4.titles=1; 
		rcb4.homeGround="Chinnaswamy Stadium"; 
		abg4.rcb=rcb4; 
		abg4.getGroupDetails();
        AdithyaBirlaGroup abg5 = new AdithyaBirlaGroup(); 
		abg5.groupId=5; 
		abg5.groupName="ABG_Division_5"; 
		abg5.sector="Mining"; 
		abg5.headquarters="Mumbai"; 
		abg5.revenue=12500.0; 
		RCB rcb5=new RCB(); 
		rcb5.teamId=1305; 
		rcb5.teamName="RCB_Squad_5"; 
		rcb5.captain="Captain_5"; 
		rcb5.titles=2; 
		rcb5.homeGround="Chinnaswamy Stadium"; 
		abg5.rcb=rcb5; abg5.getGroupDetails();
        AdithyaBirlaGroup abg6 = new AdithyaBirlaGroup(); 
		abg6.groupId=6; 
		abg6.groupName="ABG_Division_6"; 
		abg6.sector="Cement"; 
		abg6.headquarters="Mumbai"; 
		abg6.revenue=13000.0; 
		RCB rcb6=new RCB(); 
		rcb6.teamId=1306; 
		rcb6.teamName="RCB_Squad_6"; r
		rcb6.captain="Captain_6"; 
		rcb6.titles=0; 
		rcb6.homeGround="Chinnaswamy Stadium"; 
		abg6.rcb=rcb6; 
		abg6.getGroupDetails();
        AdithyaBirlaGroup abg7 = new AdithyaBirlaGroup(); 
		abg7.groupId=7; 
		abg7.groupName="ABG_Division_7"; 
		abg7.sector="Telecom"; 
		abg7.headquarters="Mumbai"; 
		abg7.revenue=13500.0; 
		RCB rcb7=new RCB(); 
		rcb7.teamId=1307; 
		rcb7.teamName="RCB_Squad_7"; 
		rcb7.captain="Captain_7"; 
		rcb7.titles=1; 
		rcb7.homeGround="Chinnaswamy Stadium"; 
		abg7.rcb=rcb7; 
		abg7.getGroupDetails();
        AdithyaBirlaGroup abg8 = new AdithyaBirlaGroup(); 
		abg8.groupId=8; 
		abg8.groupName="ABG_Division_8"; 
		abg8.sector="Fashion"; 
		abg8.headquarters="Mumbai"; 
		abg8.revenue=14000.0; 
		RCB rcb8=new RCB(); 
		rcb8.teamId=1308; 
		rcb8.teamName="RCB_Squad_8"; 
		rcb8.captain="Captain_8"; 
		rcb8.titles=2; 
		rcb8.homeGround="Chinnaswamy Stadium"; 
		abg8.rcb=rcb8; 
		abg8.getGroupDetails();
        AdithyaBirlaGroup abg9 = new AdithyaBirlaGroup(); 
		abg9.groupId=9; 
		abg9.groupName="ABG_Division_9"; 
		abg9.sector="Finance"; 
		abg9.headquarters="Mumbai"; 
		abg9.revenue=14500.0; 
		RCB rcb9=new RCB(); 
		rcb9.teamId=1309; 
		rcb9.teamName="RCB_Squad_9"; 
		rcb9.captain="Captain_9"; 
		rcb9.titles=0; 
		rcb9.homeGround="Chinnaswamy Stadium"; 
		abg9.rcb=rcb9; 
		abg9.getGroupDetails();
        AdithyaBirlaGroup abg10 = new AdithyaBirlaGroup(); 
		abg10.groupId=10; 
		abg10.groupName="ABG_Division_10"; 
		abg10.sector="Mining"; 
		abg10.headquarters="Mumbai"; 
		abg10.revenue=15000.0; 
		RCB rcb10=new RCB(); 
		rcb10.teamId=1310; 
		rcb10.teamName="RCB_Squad_10"; 
		rcb10.captain="Captain_10"; 
		rcb10.titles=1; 
		rcb10.homeGround="Chinnaswamy Stadium"; 
		abg10.rcb=rcb10; 
		abg10.getGroupDetails();
        AdithyaBirlaGroup abg11 = new AdithyaBirlaGroup(); 
		abg11.groupId=11; 
		abg11.groupName="ABG_Division_11"; 
		abg11.sector="Cement"; 
		abg11.headquarters="Mumbai"; 
		abg11.revenue=15500.0; 
		RCB rcb11=new RCB(); 
		rcb11.teamId=1311; 
		rcb11.teamName="RCB_Squad_11"; 
		rcb11.captain="Captain_11"; 
		rcb11.titles=2; 
		rcb11.homeGround="Chinnaswamy Stadium"; 
		abg11.rcb=rcb11; 
		abg11.getGroupDetails();
        AdithyaBirlaGroup abg12 = new AdithyaBirlaGroup(); 
		abg12.groupId=12; 
		abg12.groupName="ABG_Division_12"; 
		abg12.sector="Telecom"; 
		abg12.headquarters="Mumbai"; 
		abg12.revenue=16000.0; 
		RCB rcb12=new RCB(); 
		rcb12.teamId=1312; 
		rcb12.teamName="RCB_Squad_12"; 
		rcb12.captain="Captain_12"; 
		rcb12.titles=0; 
		rcb12.homeGround="Chinnaswamy Stadium"; 
		abg12.rcb=rcb12; 
		abg12.getGroupDetails();
        AdithyaBirlaGroup abg13 = new AdithyaBirlaGroup(); 
		abg13.groupId=13; 
		abg13.groupName="ABG_Division_13"; 
		abg13.sector="Fashion"; 
		abg13.headquarters="Mumbai"; 
		abg13.revenue=16500.0; 
		RCB rcb13=new RCB(); 
		rcb13.teamId=1313; 
		rcb13.teamName="RCB_Squad_13"; 
		rcb13.captain="Captain_13"; 
		rcb13.titles=1; 
		rcb13.homeGround="Chinnaswamy Stadium"; 
		abg13.rcb=rcb13; 
		abg13.getGroupDetails();
        AdithyaBirlaGroup abg14 = new AdithyaBirlaGroup(); 
		abg14.groupId=14; 
		abg14.groupName="ABG_Division_14"; 
		abg14.sector="Finance"; 
		abg14.headquarters="Mumbai"; 
		abg14.revenue=17000.0; 
		RCB rcb14=new RCB(); 
		rcb14.teamId=1314; 
		rcb14.teamName="RCB_Squad_14"; 
		rcb14.captain="Captain_14"; 
		rcb14.titles=2; 
		rcb14.homeGround="Chinnaswamy Stadium"; 
		abg14.rcb=rcb14; 
		abg14.getGroupDetails();
        AdithyaBirlaGroup abg15 = new AdithyaBirlaGroup(); 
		abg15.groupId=15; 
		abg15.groupName="ABG_Division_15"; 
		abg15.sector="Mining"; abg15.headquarters="Mumbai"; abg15.revenue=17500.0; RCB rcb15=new RCB(); rcb15.teamId=1315; rcb15.teamName="RCB_Squad_15"; rcb15.captain="Captain_15"; rcb15.titles=0; rcb15.homeGround="Chinnaswamy Stadium"; abg15.rcb=rcb15; abg15.getGroupDetails();
        AdithyaBirlaGroup abg16 = new AdithyaBirlaGroup(); abg16.groupId=16; abg16.groupName="ABG_Division_16"; abg16.sector="Cement"; abg16.headquarters="Mumbai"; abg16.revenue=18000.0; RCB rcb16=new RCB(); rcb16.teamId=1316; rcb16.teamName="RCB_Squad_16"; rcb16.captain="Captain_16"; rcb16.titles=1; rcb16.homeGround="Chinnaswamy Stadium"; abg16.rcb=rcb16; abg16.getGroupDetails();
        AdithyaBirlaGroup abg17 = new AdithyaBirlaGroup(); abg17.groupId=17; abg17.groupName="ABG_Division_17"; abg17.sector="Telecom"; abg17.headquarters="Mumbai"; abg17.revenue=18500.0; RCB rcb17=new RCB(); rcb17.teamId=1317; rcb17.teamName="RCB_Squad_17"; rcb17.captain="Captain_17"; rcb17.titles=2; rcb17.homeGround="Chinnaswamy Stadium"; abg17.rcb=rcb17; abg17.getGroupDetails();
        AdithyaBirlaGroup abg18 = new AdithyaBirlaGroup(); abg18.groupId=18; abg18.groupName="ABG_Division_18"; abg18.sector="Fashion"; abg18.headquarters="Mumbai"; abg18.revenue=19000.0; RCB rcb18=new RCB(); rcb18.teamId=1318; rcb18.teamName="RCB_Squad_18"; rcb18.captain="Captain_18"; rcb18.titles=0; rcb18.homeGround="Chinnaswamy Stadium"; abg18.rcb=rcb18; abg18.getGroupDetails();
        AdithyaBirlaGroup abg19 = new AdithyaBirlaGroup(); abg19.groupId=19; abg19.groupName="ABG_Division_19"; abg19.sector="Finance"; abg19.headquarters="Mumbai"; abg19.revenue=19500.0; RCB rcb19=new RCB(); rcb19.teamId=1319; rcb19.teamName="RCB_Squad_19"; rcb19.captain="Captain_19"; rcb19.titles=1; rcb19.homeGround="Chinnaswamy Stadium"; abg19.rcb=rcb19; abg19.getGroupDetails();
        AdithyaBirlaGroup abg20 = new AdithyaBirlaGroup(); abg20.groupId=20; abg20.groupName="ABG_Division_20"; abg20.sector="Mining"; abg20.headquarters="Mumbai"; abg20.revenue=20000.0; RCB rcb20=new RCB(); rcb20.teamId=1320; rcb20.teamName="RCB_Squad_20"; rcb20.captain="Captain_20"; rcb20.titles=2; rcb20.homeGround="Chinnaswamy Stadium"; abg20.rcb=rcb20; abg20.getGroupDetails();
    }
}
