class MobileExecutor 
{
    public static void main(String[] args) 
	{
        Mobile m1 = new Mobile();
        m1.mobileId=1;
        m1.brand="Samsung";
        m1.model="Galaxy S21";
        m1.color="Black";
        SIM s1=new SIM();
        s1.simNumber="6197392793";
        s1.operator="Jio";
        s1.planType="Prepaid";
        s1.balance=50.0;
        s1.validity= "30 days";
        m1.sim=s1;
        m1.getMobileDetails();

        Mobile m2 = new Mobile();
        m2.mobileId = 2;
        m2.brand = "Apple";
        m2.model = "iPhone 14";
        m2.color = "White";
        SIM s2 = new SIM();
        s2.simNumber = "7239736202";
        s2.operator = "Airtel";
        s2.planType = "Postpaid";
        s2.balance = 0.0;
        s2.validity = "Monthly";
        m2.sim = s2;
        m2.getMobileDetails();

        Mobile m3 = new Mobile();
        m3.mobileId = 3;
        m3.brand = "OnePlus";
        m3.model = "11R";
        m3.color = "Green";
        SIM s3 = new SIM();
        s3.simNumber = "3528360287";
        s3.operator = "Vi";
        s3.planType = "Prepaid";
        s3.balance = 30.0;
        s3.validity = "28 days";
        m3.sim = s3;
        m3.getMobileDetails();

        Mobile m4 = new Mobile();
        m4.mobileId = 4;
        m4.brand = "Xiaomi";
        m4.model = "Redmi Note 12";
        m4.color = "Blue";
        SIM s4 = new SIM();
        s4.simNumber = "8668936734";
        s4.operator = "BSNL";
        s4.planType = "Prepaid";
        s4.balance = 20.0;
        s4.validity = "30 days";
        m4.sim = s4;
        m4.getMobileDetails();

        Mobile m5 = new Mobile();
        m5.mobileId = 5;
        m5.brand = "Realme";
        m5.model = "GT Neo 5";
        m5.color = "Gold";
        SIM s5 = new SIM();
        s5.simNumber = "1460002578";
        s5.operator = "Jio";
        s5.planType = "Postpaid";
        s5.balance = 0.0;
        s5.validity = "Monthly";
        m5.sim = s5;
        m5.getMobileDetails();

        Mobile m6 = new Mobile();
        m6.mobileId = 6;
        m6.brand = "Samsung";
        m6.model = "Galaxy A54";
        m6.color = "Violet";
        SIM s6 = new SIM();
        s6.simNumber = "3679002638";
        s6.operator = "Airtel";
        s6.planType = "Prepaid";
        s6.balance = 75.0;
        s6.validity = "56 days";
        m6.sim = s6;
        m6.getMobileDetails();

        Mobile m7 = new Mobile();
        m7.mobileId = 7;
        m7.brand = "Apple";
        m7.model = "iPhone 13";
        m7.color = "Red";
        SIM s7 = new SIM();
        s7.simNumber = "845604513";
        s7.operator = "Jio";
        s7.planType = "Postpaid";
        s7.balance = 0.0;
        s7.validity = "Monthly";
        m7.sim = s7;
        m7.getMobileDetails();

        Mobile m8 = new Mobile();
        m8.mobileId = 8;
        m8.brand = "OnePlus";
        m8.model = "Nord CE 3";
        m8.color = "Grey";
        SIM s8 = new SIM();
        s8.simNumber = "8246619483";
        s8.operator = "Vi";
        s8.planType = "Prepaid";
        s8.balance = 45.0;
        s8.validity = "28 days";
        m8.sim = s8;
        m8.getMobileDetails();

        Mobile m9 = new Mobile();
        m9.mobileId = 9;
        m9.brand = "Xiaomi";
        m9.model = "Mi 13";
        m9.color = "Black";
        SIM s9 = new SIM();
        s9.simNumber = "8973615193";
        s9.operator = "Airtel";
        s9.planType = "Prepaid";
        s9.balance = 60.0;
        s9.validity = "30 days";
        m9.sim = s9;
        m9.getMobileDetails();

        Mobile m10 = new Mobile();
        m10.mobileId = 10;
        m10.brand = "Realme";
        m10.model = "Narzo 60";
        m10.color = "Silver";
        SIM s10 = new SIM();
        s10.simNumber = "8578104851";
        s10.operator = "BSNL";
        s10.planType = "Postpaid";
        s10.balance = 0.0;
        s10.validity = "Monthly";
        m10.sim = s10;
        m10.getMobileDetails();

        Mobile m11 = new Mobile();
        m11.mobileId = 11;
        m11.brand = "Samsung";
        m11.model = "Galaxy M34";
        m11.color = "Blue";
        SIM s11 = new SIM();
        s11.simNumber = "9308249403";
        s11.operator = "Jio";
        s11.planType = "Prepaid";
        s11.balance = 25.0;
        s11.validity = "28 days";
        m11.sim = s11;
        m11.getMobileDetails();

        Mobile m12 = new Mobile();
        m12.mobileId = 12;
        m12.brand = "Apple";
        m12.model = "iPhone 12";
        m12.color = "White";
        SIM s12 = new SIM();
        s12.simNumber = "2431930284";
        s12.operator = "Airtel";
        s12.planType = "Postpaid";
        s12.balance = 0.0;
        s12.validity = "Monthly";
        m12.sim = s12;
        m12.getMobileDetails();

        Mobile m13 = new Mobile();
        m13.mobileId = 13;
        m13.brand = "OnePlus";
        m13.model = "10T";
        m13.color = "Jade Green";
        SIM s13 = new SIM();
        s13.simNumber = "8342438595";
        s13.operator = "Vi";
        s13.planType = "Prepaid";
        s13.balance = 80.0;
        s13.validity = "56 days";
        m13.sim = s13;
        m13.getMobileDetails();

        Mobile m14 = new Mobile();
        m14.mobileId = 14;
        m14.brand = "Xiaomi";
        m14.model = "Redmi 12C";
        m14.color = "Mint Green";
        SIM s14 = new SIM();
        s14.simNumber = "84639277460";
        s14.operator = "Jio";
        s14.planType = "Prepaid";
        s14.balance = 15.0;
        s14.validity = "30 days";
        m14.sim = s14;
        m14.getMobileDetails();

        Mobile m15 = new Mobile();
        m15.mobileId = 15;
        m15.brand = "Realme";
        m15.model = "C55";
        m15.color = "Rainforest";
        SIM s15 = new SIM();
        s15.simNumber = "89782983739";
        s15.operator = "BSNL";
        s15.planType = "Prepaid";
        s15.balance = 35.0;
        s15.validity = "28 days";
        m15.sim = s15;
        m15.getMobileDetails();

        Mobile m16 = new Mobile();
        m16.mobileId = 16;
        m16.brand = "Samsung";
        m16.model = "Galaxy F54";
        m16.color = "Meteor Blue";
        SIM s16 = new SIM();
        s16.simNumber = "3628263028";
        s16.operator = "Airtel";
        s16.planType = "Postpaid";
        s16.balance = 0.0;
        s16.validity = "Monthly";
        m16.sim = s16;
        m16.getMobileDetails();

        Mobile m17 = new Mobile();
        m17.mobileId = 17;
        m17.brand = "Apple";
        m17.model = "iPhone SE";
        m17.color = "Midnight";
        SIM s17 = new SIM();
        s17.simNumber = "89706846392";
        s17.operator = "Jio";
        s17.planType = "Prepaid";
        s17.balance = 55.0;
        s17.validity = "30 days";
        m17.sim = s17;
        m17.getMobileDetails();

        Mobile m18 = new Mobile();
        m18.mobileId = 18;
        m18.brand = "OnePlus";
        m18.model = "9RT";
        m18.color = "Nano Silver";
        SIM s18 = new SIM();
        s18.simNumber = "8234419485";
        s18.operator = "Airtel";
        s18.planType = "Prepaid";
        s18.balance = 40.0;
        s18.validity = "84 days";
        m18.sim = s18;
        m18.getMobileDetails();

        Mobile m19 = new Mobile();
        m19.mobileId = 19;
        m19.brand = "Xiaomi";
        m19.model = "Redmi K60";
        m19.color = "Black";
        SIM s19 = new SIM();
        s19.simNumber = "8956976493";
        s19.operator = "Vi";
        s19.planType = "Postpaid";
        s19.balance = 0.0;
        s19.validity = "Monthly";
        m19.sim = s19;
        m19.getMobileDetails();

        Mobile m20 = new Mobile();
        m20.mobileId = 20;
        m20.brand = "Realme";
        m20.model = "11 Pro";
        m20.color = "Sunrise Beige";
        SIM s20 = new SIM();
        s20.simNumber = "8234100780";
        s20.operator = "BSNL";
        s20.planType = "Prepaid";
        s20.balance = 90.0;
        s20.validity = "30 days";
        m20.sim = s20;
        m20.getMobileDetails();

    }
}
