class OttPlatformExecutor 
{
    public static void main(String[] args) 
	{
        OttPlatform ott1 = new OttPlatform();
		ott1.platformId=1; 
		ott1.platformName="Netflix"; 
		ott1.country="India"; 
		ott1.totalContent=1100; 
		ott1.language="English"; 
		Subscription sub1=new Subscription(); 
		sub1.subscriptionId=1501; 
		sub1.planName="Mobile"; 
		sub1.price=99.0; 
		sub1.screens=1;
		sub1.validity="Yearly";
		ott1.subscription=sub1; 
		ott1.getOttDetails();
        OttPlatform ott2 = new OttPlatform();
		ott2.platformId=2; 
		ott2.platformName="Amazon Prime"; 
		ott2.country="India"; 
		ott2.totalContent=1200; 
		ott2.language="Hindi"; 
		Subscription sub2=new Subscription();
		sub2.subscriptionId=1502; 
		sub2.planName="Basic"; 
		sub2.price=199.0; 
		sub2.screens=2;
		sub2.validity="Monthly";
		ott2.subscription=sub2; 
		ott2.getOttDetails();
        OttPlatform ott3 = new OttPlatform(); 
		ott3.platformId=3; 
		ott3.platformName="Hotstar"; 
		ott3.country="India";
		ott3.totalContent=1300;
		ott3.language="English"; 
		Subscription sub3=new Subscription(); 
		sub3.subscriptionId=1503; 
		sub3.planName="Standard"; 
		sub3.price=299.0; sub3.screens=3; 
		sub3.validity="Yearly"; 
		ott3.subscription=sub3; 
		ott3.getOttDetails();
        OttPlatform ott4 = new OttPlatform(); 
		ott4.platformId=4; 
		ott4.platformName="SonyLiv"; 
		ott4.country="India"; 
		ott4.totalContent=1400; 
		ott4.language="Hindi"; 
		Subscription sub4=new Subscription(); 
		sub4.subscriptionId=1504; 
		sub4.planName="Premium"; 
		sub4.price=399.0; 
		sub4.screens=4;
		sub4.validity="Monthly"; 
		ott4.subscription=sub4; 
		ott4.getOttDetails();
        OttPlatform ott5 = new OttPlatform();
		ott5.platformId=5; 
		ott5.platformName="ZEE5";
		ott5.country="India";
		ott5.totalContent=1500;
		ott5.language="English";
		Subscription sub5=new Subscription();
		sub5.subscriptionId=1505;
		sub5.planName="Mobile"; 
		sub5.price=99.0; 
		sub5.screens=1;
		sub5.validity="Yearly";
		ott5.subscription=sub5;
		ott5.getOttDetails();
        OttPlatform ott6 = new OttPlatform();
		ott6.platformId=6; 
		ott6.platformName="Voot"; 
		ott6.country="India"; 
		ott6.totalContent=1600; 
		ott6.language="Hindi"; 
		Subscription sub6=new Subscription(); 
		sub6.subscriptionId=1506;
		sub6.planName="Basic"; 
		sub6.price=199.0
		sub6.screens=2;
		sub6.validity="Monthly";
		ott6.subscription=sub6; 
		ott6.getOttDetails();
        OttPlatform ott7 = new OttPlatform(); 
		ott7.platformId=7; 
		ott7.platformName="Jio Cinema"; 
		ott7.country="India"; 
		ott7.totalContent=1700; 
		ott7.language="English"; 
		Subscription sub7=new Subscription(); 
		sub7.subscriptionId=1507;
		sub7.planName="Standard"; 
		sub7.price=299.0; 
		sub7.screens=3; sub7.validity="Yearly"; 
		ott7.subscription=sub7; 
		ott7.getOttDetails();
        OttPlatform ott8 = new OttPlatform(); 
		ott8.platformId=8;
		ott8.platformName="Netflix";
		ott8.country="India";
		ott8.totalContent=1800;
		ott8.language="Hindi"; 
		Subscription sub8=new Subscription(); 
		sub8.subscriptionId=1508; 
		sub8.planName="Premium"; 
		sub8.price=399.0; sub8.screens=4;
		sub8.validity="Monthly"; 
		ott8.subscription=sub8; 
		ott8.getOttDetails();
        OttPlatform ott9 = new OttPlatform(); 
		ott9.platformId=9; 
		ott9.platformName="Amazon Prime";
		ott9.country="India"; 
		ott9.totalContent=1900; 
		ott9.language="English";
		Subscription sub9=new Subscription();
		sub9.subscriptionId=1509; 
		sub9.planName="Mobile"; 
		sub9.price=99.0; sub9.screens=1; 
		sub9.validity="Yearly"; 
		ott9.subscription=sub9; 
		ott9.getOttDetails();
        OttPlatform ott10 = new OttPlatform(); 
		ott10.platformId=10; 
		ott10.platformName="Hotstar"; 
		ott10.country="India"; 
		ott10.totalContent=2000;
		ott10.language="Hindi";
		Subscription sub10=new Subscription(); 
		sub10.subscriptionId=1510; 
		sub10.planName="Basic"; 
		sub10.price=199.0; 
		sub10.screens=2;
		sub10.validity="Monthly"; 
		ott10.subscription=sub10; 
		ott10.getOttDetails();
        OttPlatform ott11 = new OttPlatform(); 
		ott11.platformId=11; 
		ott11.platformName="SonyLiv";
		ott11.country="India"; 
		ott11.totalContent=2100;
		ott11.language="English
		Subscription sub11=new Subscription();
		sub11.subscriptionId=1511; 
		sub11.planName="Standard"; 
		sub11.price=299.0; sub11.screens=3; 
		sub11.validity="Yearly";
		ott11.subscription=sub11;
		ott11.getOttDetails();
        OttPlatform ott12 = new OttPlatform(); 
		ott12.platformId=12;
		ott12.platformName="ZEE5";
		ott12.country="India";
		ott12.totalContent=2200; 
		ott12.language="Hindi";
		Subscription sub12=new Subscription(); 
		sub12.subscriptionId=1512;
		sub12.planName="Premium"; 
		sub12.price=399.0; 
		sub12.screens=4;
		sub12.validity="Monthly";
		ott12.subscription=sub12;
		ott12.getOttDetails();
        OttPlatform ott13 = new OttPlatform(); 
		ott13.platformId=13; 
		ott13.platformName="Voot"; 
		ott13.country="India"; 
		ott13.totalContent=2300; 
		ott13.language="English";
		Subscription sub13=new Subscription(); 
		sub13.subscriptionId=1513;
		sub13.planName="Mobile"; 
		sub13.price=99.0;
		sub13.screens=1; 
		sub13.validity="Yearly";
		ott13.subscription=sub13; 
		ott13.getOttDetails();
        OttPlatform ott14 = new OttPlatform();
		ott14.platformId=14; 
		ott14.platformName="Jio Cinema"; 
		ott14.country="India"; 
		ott14.totalContent=2400;
		ott14.language="Hindi"; 
		Subscription sub14=new Subscription();
		sub14.subscriptionId=1514;
		sub14.planName="Basic";
		sub14.price=199.0;
		sub14.screens=2;
		sub14.validity="Monthly"; 
		ott14.subscription=sub14; 
		ott14.getOttDetails();
        OttPlatform ott15 = new OttPlatform();
		ott15.platformId=15; 
		ott15.platformName="Netflix";
		ott15.country="India";
		ott15.totalContent=2500; 
		ott15.language="English";
		Subscription sub15=new Subscription(); 
		sub15.subscriptionId=1515;
		sub15.planName="Standard";
		sub15.price=299.0; 
		sub15.screens=3;
		sub15.validity="Yearly";
		ott15.subscription=sub15;
		ott15.getOttDetails();
        OttPlatform ott16 = new OttPlatform(); 
		ott16.platformId=16; 
		ott16.platformName="Amazon Prime"; 
		ott16.country="India"; 
		ott16.totalContent=2600; 
		ott16.language="Hindi"; 
		Subscription sub16=new Subscription(); 
		sub16.subscriptionId=1516; 
		sub16.planName="Premium"; 
		sub16.price=399.0; 
		sub16.screens=4; 
		sub16.validity="Monthly";
		ott16.subscription=sub16;
		ott16.getOttDetails();
        OttPlatform ott17 = new OttPlatform();
		ott17.platformId=17; 
		ott17.platformName="Hotstar";
		ott17.country="India"; 
		ott17.totalContent=2700;
		ott17.language="English"; 
		Subscription sub17=new Subscription(); 
		sub17.subscriptionId=1517; 
		sub17.planName="Mobile";
		sub17.price=99.0; 
		sub17.screens=1;
		sub17.validity="Yearly";
		ott17.subscription=sub17; 
		ott17.getOttDetails();
        OttPlatform ott18 = new OttPlatform();
		ott18.platformId=18; 
		ott18.platformName="SonyLiv"; 
		ott18.country="India";
		ott18.totalContent=2800; 
		ott18.language="Hindi";
		Subscription sub18=new Subscription();
		sub18.subscriptionId=1518; 
		sub18.planName="Basic"; 
		sub18.price=199.0; 
		sub18.screens=2;
		sub18.validity="Monthly";
		ott18.subscription=sub18; 
		ott18.getOttDetails();
        OttPlatform ott19 = new OttPlatform(); 
		ott19.platformId=19; 
		ott19.platformName="ZEE5";
		ott19.country="India"; 
		ott19.totalContent=2900;
		ott19.language="English";
		Subscription sub19=new Subscription(); 
		sub19.subscriptionId=1519;
		sub19.planName="Standard";
		sub19.price=299.0; 
		sub19.screens=3; 
		sub19.validity="Yearly"; 
		ott19.subscription=sub19;
		ott19.getOttDetails();
        OttPlatform ott20 = new OttPlatform(); 
		ott20.platformId=20; 
		ott20.platformName="Voot";
		ott20.country="India";
		ott20.totalContent=3000; 
		ott20.language="Hindi"; 
		Subscription sub20=new Subscription();
		sub20.subscriptionId=1520;
		sub20.planName="Premium"; 
		sub20.price=399.0; 
		sub20.screens=4; 
		sub20.validity="Monthly";
		ott20.subscription=sub20; 
		ott20.getOttDetails();
    }
}
