class RailwayStationExecutor 
{
    public static void main(String[] args) 
	{

        RailwayStation rs1 = new RailwayStation();
        rs1.stationId = 1;
        rs1.stationName = "Bangalore City";
        rs1.city = "Bangalore";
        rs1.totalPlatforms = 10;
        rs1.zone = "South";
        Platform pl1 = new Platform();
        pl1.platformNumber = 1;
        pl1.trainName = "Rajdhani Express";
        pl1.arrivalTime = "06:00";
        pl1.departureTime = "06:30";
        pl1.status = "On Time";
        rs1.platform = pl1;
        rs1.getStationDetails();

        RailwayStation rs2 = new RailwayStation();
        rs2.stationId = 2;
        rs2.stationName = "Mumbai Central";
        rs2.city = "Mumbai";
        rs2.totalPlatforms = 14;
        rs2.zone = "West";
        Platform pl2 = new Platform();
        pl2.platformNumber = 2;
        pl2.trainName = "Shatabdi Express";
        pl2.arrivalTime = "07:00";
        pl2.departureTime = "07:30";
        pl2.status = "Delayed";
        rs2.platform = pl2;
        rs2.getStationDetails();

        RailwayStation rs3 = new RailwayStation();
        rs3.stationId = 3;
        rs3.stationName = "New Delhi";
        rs3.city = "Delhi";
        rs3.totalPlatforms = 16;
        rs3.zone = "North";
        Platform pl3 = new Platform();
        pl3.platformNumber = 3;
        pl3.trainName = "Duronto Express";
        pl3.arrivalTime = "08:00";
        pl3.departureTime = "08:45";
        pl3.status = "On Time";
        rs3.platform = pl3;
        rs3.getStationDetails();

        RailwayStation rs4 = new RailwayStation();
        rs4.stationId = 4;
        rs4.stationName = "Chennai Central";
        rs4.city = "Chennai";
        rs4.totalPlatforms = 12;
        rs4.zone = "South";
        Platform pl4 = new Platform();
        pl4.platformNumber = 4;
        pl4.trainName = "Vande Bharat";
        pl4.arrivalTime = "09:00";
        pl4.departureTime = "09:15";
        pl4.status = "On Time";
        rs4.platform = pl4;
        rs4.getStationDetails();

        RailwayStation rs5 = new RailwayStation();
        rs5.stationId = 5;
        rs5.stationName = "Howrah Junction";
        rs5.city = "Kolkata";
        rs5.totalPlatforms = 23;
        rs5.zone = "East";
        Platform pl5 = new Platform();
        pl5.platformNumber = 5;
        pl5.trainName = "Garib Rath";
        pl5.arrivalTime = "10:00";
        pl5.departureTime = "10:30";
        pl5.status = "Delayed";
        rs5.platform = pl5;
        rs5.getStationDetails();

        RailwayStation rs6 = new RailwayStation();
        rs6.stationId = 6;
        rs6.stationName = "Hyderabad Deccan";
        rs6.city = "Hyderabad";
        rs6.totalPlatforms = 8;
        rs6.zone = "South";
        Platform pl6 = new Platform();
        pl6.platformNumber = 6;
        pl6.trainName = "Jan Shatabdi";
        pl6.arrivalTime = "11:00";
        pl6.departureTime = "11:20";
        pl6.status = "On Time";
        rs6.platform = pl6;
        rs6.getStationDetails();

        RailwayStation rs7 = new RailwayStation();
        rs7.stationId = 7;
        rs7.stationName = "Pune Junction";
        rs7.city = "Pune";
        rs7.totalPlatforms = 6;
        rs7.zone = "West";
        Platform pl7 = new Platform();
        pl7.platformNumber = 1;
        pl7.trainName = "Deccan Express";
        pl7.arrivalTime = "12:00";
        pl7.departureTime = "12:30";
        pl7.status = "On Time";
        rs7.platform = pl7;
        rs7.getStationDetails();

        RailwayStation rs8 = new RailwayStation();
        rs8.stationId = 8;
        rs8.stationName = "Ahmedabad Junction";
        rs8.city = "Ahmedabad";
        rs8.totalPlatforms = 10;
        rs8.zone = "West";
        Platform pl8 = new Platform();
        pl8.platformNumber = 2;
        pl8.trainName = "Gujarat Express";
        pl8.arrivalTime = "13:00";
        pl8.departureTime = "13:30";
        pl8.status = "Delayed";
        rs8.platform = pl8;
        rs8.getStationDetails();

        RailwayStation rs9 = new RailwayStation();
        rs9.stationId = 9;
        rs9.stationName = "Jaipur Junction";
        rs9.city = "Jaipur";
        rs9.totalPlatforms = 6;
        rs9.zone = "North";
        Platform pl9 = new Platform();
        pl9.platformNumber = 3;
        pl9.trainName = "Pink City Express";
        pl9.arrivalTime = "14:00";
        pl9.departureTime = "14:20";
        pl9.status = "On Time";
        rs9.platform = pl9;
        rs9.getStationDetails();

        RailwayStation rs10 = new RailwayStation();
        rs10.stationId = 10;
        rs10.stationName = "Lucknow Charbagh";
        rs10.city = "Lucknow";
        rs10.totalPlatforms = 9;
        rs10.zone = "North";
        Platform pl10 = new Platform();
        pl10.platformNumber = 4;
        pl10.trainName = "Lucknow Mail";
        pl10.arrivalTime = "15:00";
        pl10.departureTime = "15:40";
        pl10.status = "On Time";
        rs10.platform = pl10;
        rs10.getStationDetails();

        RailwayStation rs11 = new RailwayStation();
        rs11.stationId = 11;
        rs11.stationName = "Patna Junction";
        rs11.city = "Patna";
        rs11.totalPlatforms = 10;
        rs11.zone = "East";
        Platform pl11 = new Platform();
        pl11.platformNumber = 5;
        pl11.trainName = "Patna Express";
        pl11.arrivalTime = "16:00";
        pl11.departureTime = "16:30";
        pl11.status = "Delayed";
        rs11.platform = pl11;
        rs11.getStationDetails();

        RailwayStation rs12 = new RailwayStation();
        rs12.stationId = 12;
        rs12.stationName = "Bhopal Junction";
        rs12.city = "Bhopal";
        rs12.totalPlatforms = 7;
        rs12.zone = "West";
        Platform pl12 = new Platform();
        pl12.platformNumber = 6;
        pl12.trainName = "Bhopal Express";
        pl12.arrivalTime = "17:00";
        pl12.departureTime = "17:15";
        pl12.status = "On Time";
        rs12.platform = pl12;
        rs12.getStationDetails();

        RailwayStation rs13 = new RailwayStation();
        rs13.stationId = 13;
        rs13.stationName = "Nagpur Junction";
        rs13.city = "Nagpur";
        rs13.totalPlatforms = 8;
        rs13.zone = "South";
        Platform pl13 = new Platform();
        pl13.platformNumber = 1;
        pl13.trainName = "Vidarbha Express";
        pl13.arrivalTime = "18:00";
        pl13.departureTime = "18:30";
        pl13.status = "On Time";
        rs13.platform = pl13;
        rs13.getStationDetails();

        RailwayStation rs14 = new RailwayStation();
        rs14.stationId = 14;
        rs14.stationName = "Kochi Junction";
        rs14.city = "Kochi";
        rs14.totalPlatforms = 5;
        rs14.zone = "South";
        Platform pl14 = new Platform();
        pl14.platformNumber = 2;
        pl14.trainName = "Kerala Express";
        pl14.arrivalTime = "19:00";
        pl14.departureTime = "19:25";
        pl14.status = "On Time";
        rs14.platform = pl14;
        rs14.getStationDetails();

        RailwayStation rs15 = new RailwayStation();
        rs15.stationId = 15;
        rs15.stationName = "Surat Junction";
        rs15.city = "Surat";
        rs15.totalPlatforms = 6;
        rs15.zone = "West";
        Platform pl15 = new Platform();
        pl15.platformNumber = 3;
        pl15.trainName = "Surat Express";
        pl15.arrivalTime = "20:00";
        pl15.departureTime = "20:30";
        pl15.status = "Delayed";
        rs15.platform = pl15;
        rs15.getStationDetails();

        RailwayStation rs16 = new RailwayStation();
        rs16.stationId = 16;
        rs16.stationName = "Indore Junction";
        rs16.city = "Indore";
        rs16.totalPlatforms = 5;
        rs16.zone = "West";
        Platform pl16 = new Platform();
        pl16.platformNumber = 4;
        pl16.trainName = "Indore Express";
        pl16.arrivalTime = "21:00";
        pl16.departureTime = "21:20";
        pl16.status = "On Time";
        rs16.platform = pl16;
        rs16.getStationDetails();

        RailwayStation rs17 = new RailwayStation();
        rs17.stationId = 17;
        rs17.stationName = "Coimbatore Junction";
        rs17.city = "Coimbatore";
        rs17.totalPlatforms = 6;
        rs17.zone = "South";
        Platform pl17 = new Platform();
        pl17.platformNumber = 5;
        pl17.trainName = "Kovai Express";
        pl17.arrivalTime = "22:00";
        pl17.departureTime = "22:30";
        pl17.status = "On Time";
        rs17.platform = pl17;
        rs17.getStationDetails();

        RailwayStation rs18 = new RailwayStation();
        rs18.stationId = 18;
        rs18.stationName = "Visakhapatnam";
        rs18.city = "Vizag";
        rs18.totalPlatforms = 7;
        rs18.zone = "South";
        Platform pl18 = new Platform();
        pl18.platformNumber = 6;
        pl18.trainName = "Vizag Express";
        pl18.arrivalTime = "06:30";
        pl18.departureTime = "07:00";
        pl18.status = "Delayed";
        rs18.platform = pl18;
        rs18.getStationDetails();

        RailwayStation rs19 = new RailwayStation();
        rs19.stationId = 19;
        rs19.stationName = "Vadodara Junction";
        rs19.city = "Vadodara";
        rs19.totalPlatforms = 7;
        rs19.zone = "West";
        Platform pl19 = new Platform();
        pl19.platformNumber = 1;
        pl19.trainName = "Vadodara Express";
        pl19.arrivalTime = "07:30";
        pl19.departureTime = "08:00";
        pl19.status = "On Time";
        rs19.platform = pl19;
        rs19.getStationDetails();

        RailwayStation rs20 = new RailwayStation();
        rs20.stationId = 20;
        rs20.stationName = "Guwahati Junction";
        rs20.city = "Guwahati";
        rs20.totalPlatforms = 6;
        rs20.zone = "Northeast";
        Platform pl20 = new Platform();
        pl20.platformNumber = 2;
        pl20.trainName = "Brahmaputra Express";
        pl20.arrivalTime = "08:30";
        pl20.departureTime = "09:00";
        pl20.status = "On Time";
        rs20.platform = pl20;
        rs20.getStationDetails();
    }
}
