class Microwave
{
	static String brand;
	static long price;
	static String model;
	static String energyConsumption;
	static String capacity;
	static String annualEnergyConsumption;
	static String installationType;
	static String partNumber;
	static String specialFeatures;
	static String ovenCookingMode;
	static String burnerType;
	static String colour;
	static String voltage;
	static String wattage;
	static String fuelType;
	static String defrostSystem;
	static String doorOrientation;
	static String material;
	static String includedComponents;
	static String batteriesIncluded;
	static String batteriesRequired;
	static String manufacturer;
	static String counteryOfOrigin;
	public static void main(String [] args)
	{
		brand="Panasonic";
		price=6440L;
		model="NN-ST26JMFDG";
		energyConsumption="800 Watts";
		capacity="20 litres";
		annualEnergyConsumption="800 Watts";
		installationType="Countertop";
		partNumber="NN-ST26JMFDG";
		specialFeatures="Defrost,Turntable,Auto Heat,Timer,Compact,Vapor Clean,Auto Cook";
		ovenCookingMode="Solo";
		burnerType="Cast Iron";
		colour="Silver";
		voltage="230 Volts";
		wattage="800 Watts";
		fuelType="Electric";
		defrostSystem="Defrost";
		doorOrientation="Left";
		material="Iron";
		includedComponents="MWO Unit, Turntable, Rotating Ring, User Manual";
		batteriesIncluded="No";
		batteriesRequired="No";
		manufacturer="Panasonic";
		counteryOfOrigin="Thiland";
		System.out.println("Microwave Brade is: "+brand);
		System.out.println("Microwave Price is: "+price);
		System.out.println("Microwave Model is: "+model);
		System.out.println("Microwave Energy Consumption is: "+energyConsumption);
		System.out.println("Microwave Capacity is: "+capacity);
		System.out.println("Microwave Annual Energy Consumption is: "+annualEnergyConsumption);
		System.out.println("Microwave Installation Type is: "+installationType);
		System.out.println("Microwave Part Number is: "+partNumber);
		System.out.println("Microwave special Features is: "+specialFeatures);
		System.out.println("Microwave Oven Cooking Mode is: "+ovenCookingMode);
		System.out.println("Microwave Burner Type is: "+burnerType);
		System.out.println("Microwave Colour is: "+colour);
		System.out.println("Microwave Voltage is: "+voltage);
		System.out.println("Microwave Wattage is: "+wattage);
		System.out.println("Microwave FuelType is: "+fuelType);
		System.out.println("Microwave Defrost System is: "+defrostSystem);
		System.out.println("Microwave DoorOrientation is: "+doorOrientation);
		System.out.println("Microwave Material is: "+material);
		System.out.println("Microwave Included Components is: "+includedComponents);
		System.out.println("Microwave Batteries Included is: "+batteriesIncluded);
		System.out.println("Microwave Batteries Required is: "+batteriesRequired);
		System.out.println("Microwave Manufacturer is: "+manufacturer);
	}
}